apps/frontend-example/package.json, package-lock.json
Noticed this was missing during a work test. The error I received upon `npm install` was:
```
sh: shx: command not found
npm error Lifecycle script `postinstall` failed with error:
npm error code 127
npm error path /Users/nathansherburn/Repos/bluedot-contributions/apps/login-account-proxy
npm error workspace @bluedot/login-account-proxy@1.0.0
npm error location /Users/nathansherburn/Repos/bluedot-contributions/apps/login-account-proxy
npm error command failed
npm error command sh -c shx cp -n .env.local.template .env.local
```
=> Add missing dev dependency for frontend-example

apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap, apps/website-25/src/__tests__/pages/about.test.tsx, apps/website-25/src/__tests__/pages/careers.test.tsx
Working version of #57 😇☺️.
See #60.
Placed the two `pages` tests into a `__tests__` directory.
Looking at the [`with-vitest`-example](https://github.com/vercel/next.js/tree/canary/examples/with-vitest) referenced by NextJS docs this seems to be the way to go.
For colocating tests next to their source files (even for `pages`) we could migrate to the [`app`-router](https://nextjs.org/docs/app), see #60 for more information.
```
Time:    3.51s 
```
=> Add test coverage for `about`- & `careers`-page

apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap, apps/website-25/src/components/about/TeamSection.tsx, apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap, apps/website-25/src/components/careers/CareersSection.tsx, apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap, apps/website-25/src/components/homepage/StorySection.tsx, apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap, libraries/ui/src/CTALinkOrButton.tsx, libraries/ui/src/Card.tsx, libraries/ui/src/__snapshots__/Card.test.tsx.snap, libraries/ui/src/__snapshots__/Section.test.tsx.snap
Add isExternalUrl options to CTALink. Update to use across pages.
- Add isExternalUrl option to CTA. Use new option in Team and JobListing
- Use new Section CTA option in home/StorySection
- Tweak some styling in Team
```
Time:    1.046s 
```
=> Add isExternalUrl options to CTALink

apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap, apps/website-25/src/components/about/HistorySection.tsx, apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap, apps/website-25/src/components/careers/CareersSection.tsx, apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap, apps/website-25/src/globals.css, libraries/ui/src/CourseCard.tsx, libraries/ui/src/shared.css
Add container-lined styles
#44 
- Added new utility class in libraries/ui shared.css
- Updated usage across existing pages and components
- Remove `now` option in JobListing as this is unused
```
Time:    1.648s 
```
=> Add container-lined styles

apps/website-25/src/components/homepage/CourseSection.tsx, apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, libraries/ui/src/CourseCard.test.tsx, libraries/ui/src/CourseCard.tsx, libraries/ui/src/Tag.test.tsx, libraries/ui/src/Tag.tsx, libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap, libraries/ui/src/__snapshots__/Tag.test.tsx.snap, libraries/ui/src/default-config/vitest.mjs, libraries/ui/src/index.ts
Add CourseCard tests and update testing approaches
- Add CourseCard tests
- Update Tag to use `{children}` instead of `{label}`
- Add BEM classes to CourseCard as needed
- Remove unused CourseCardButton
- Enabling globals configures vitest to clean up aftereach by default ([vue docs ref](https://testing-library.com/docs/vue-testing-library/setup/), [vitest docs](https://vitest.dev/config/#globals))
- Updating `image` arg to `imgSrc`
- So far, our standards have been to include [BEM](https://getbem.com/naming/) naming conventions as class names on all HTML elements
- The BEM naming convention is a cheap way to navigate the DOM both as devs (e.g., reading through Inspect tools to understand which components were used) and in more targeted testing against specific elements (e.g. so we dont …
=> Add CourseCard tests and update testing approaches

libraries/ui/src/Tag.stories.tsx
`label` was removed in #111
`storybook` UI is out of date.
:info: `storybook` is quite flexible here in the sense that the `build` did not break.
Update `Tag.stories.tsx` to match new API
```
Time:    2.751s 
```
=> Update `Tag.stories.tsx` to match new API

.vscode/extensions.json
Add `Figma for VS Code` extension to workspace recommendations.
Following up on #93.
```
Cached:    4 cached, 7 total
Time:    3.701s
```
=> Add `Figma for VS Code` extension to recommendations

libraries/ui/src/Card.test.tsx, libraries/ui/src/Card.tsx, libraries/ui/src/CourseCard.tsx
This was [discussed in a previous PR](https://github.com/bluedotimpact/bluedot/pull/153#discussion_r1937127494), but I neglected to actually include the change in the version that was merged.
Fixes # (issue)
(No visual change)
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
```
Cached:    7 cached, 7 total
Time:    228ms >>> FULL TURBO
```
=> Make <Card> footer a child rather than a prop

apps/website-25/src/components/homepage/CommunitySection/TestimonialSection.tsx, apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap, apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, libraries/ui/src/SlideList.stories.tsx, libraries/ui/src/SlideList.test.tsx, libraries/ui/src/SlideList.tsx
Make SlideList title styles optional
Fixes #197 
Fixes #196 
- Update SlideList title and description to use default typography (as defined in globals.css)
- Make title, subtitle, and description optional. Add handling for right-aligned buttons even without nav header
https://github.com/user-attachments/assets/7b4caf62-3be0-4231-abd1-85e4e228fac5
```
Time:    2.226s 
```
=> Make SlideList title styles optional

apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap, apps/website-25/src/components/about/__snapshots__/JoinUsCta.test.tsx.snap, apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap, apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap, apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap, apps/website-25/src/pages/_app.tsx, libraries/ui/src/CTALinkOrButton.tsx, libraries/ui/src/CookieBanner.stories.tsx, libraries/ui/src/CookieBanner.test.tsx, libraries/ui/src/CookieBanner.tsx, libraries/ui/src/__snapshots__/Banner.test.tsx.snap, libraries/ui/src/__snapshots__/CTALinkOrButton.test.tsx.snap, libraries/ui/src/__snapshots__/Card.test.tsx.snap, libraries/ui/src/__snapshots__/CookieBanner.test.tsx.snap, libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap, libraries/ui/src/__snapshots__/Nav.test.tsx.snap, libraries/ui/src/__snapshots__/Section.test.tsx.snap, libraries/ui/src/index.ts, libraries/ui/src/shared.css
Adds a CookieBanner, which sets a localStorage item to "accepted" or "rejected" when dismissed (in line with how the existing bluedot website works).
Fixes #158 
| 📸 |  |
| 📕 | ![Screenshot 2025-02-03 at 20 14 52](https://github.com/user-attachments/assets/3021209a-3c12-4861-ab88-e2d65c3cf505) |
| 🖥️ | ![Screenshot 2025-02-03 at 20 14 41](https://github.com/user-attachments/assets/7548346c-3a6c-4fd0-bae1-7998636fa499) |
| 📱  | ![Screenshot 2025-02-03 at 20 14 37](https://github.com/user-attachments/assets/d1673cab-64f6-40b8-aa51-5241b8a9ece3) |
```
Cached:    7 cached, 7 total
Time:    225ms >>> FULL TURBO
```
=> Add CookieBanner to homepage

apps/website-25/src/components/homepage/CommunitySection/__snapshots__/GovernanceProjects.test.tsx.snap, apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, libraries/ui/src/CourseCard.tsx, libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
Remove CourseCard ratings
Fixes #191 
- Unfortunately, we don't have course ratings yet so this feature is unavailable 🥲 
```
Time:    2.464s 
```
=> Remove CourseCard ratings

apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, apps/website-25/src/globals.css, libraries/ui/src/CourseCard.tsx, libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap, libraries/ui/src/default-config/tailwind.ts
Add `fontSize`-aliases & use them on `globals.css`.
Fixes #133.
Fixes #132.
Fixes #131.
* Use *semantically correct* `<h3>` on `FeaturedCourseCard`.
* Introduce `design-s`, ..., `design-xl` aliases equivalent to [Figma](https://www.figma.com/design/s4dNR4ELGKPbja6GkHLVJy/Website-Laura's-Working-File?node-id=879-4824&p=f&t=NUaQQCvz92d5wYqY-0).
* 📸  No visual changes.
```
Time:    3.385s 
```
=> Add `fontSize`-aliases & use them on `globals.css`

apps/website-25/src/components/homepage/BlogSection.tsx, apps/website-25/src/components/homepage/__snapshots__/BlogSection.test.tsx.snap
Update tag in blog section to stick to the right side on mobile and desktop
No issue, but related to [website MVP](https://github.com/orgs/bluedotimpact/projects/2/views/1)
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  | 
Before: 
After:
|
```
@bluedot/website-25:test:       Tests  23 passed (23)
@bluedot/website-25:test:    Start at  09:22:09
@bluedot/website-25:test:    Duration  2.36s (transform 360ms, setup 0ms, collect 12.49s, tests 343ms, environment 3.06s, prepare 1.18s)
```
=> Update tag in blog section to stick to the right side

apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap, apps/website-25/src/components/about/BeliefsSection.stories.tsx, apps/website-25/src/components/about/BeliefsSection.tsx, apps/website-25/src/components/about/__snapshots__/BeliefsSection.test.tsx.snap, apps/website-25/src/components/careers/ValuesSection.stories.tsx, apps/website-25/src/components/careers/ValuesSection.tsx, apps/website-25/src/components/careers/__snapshots__/ValuesSection.test.tsx.snap, apps/website-25/src/components/homepage/CommunitySection/TestimonialSection.tsx, apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap, apps/website-25/src/components/homepage/CourseSection.tsx, apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, libraries/ui/src/SlideList.tsx
This PR uses SlideList for ValuesSection and BeliefsSection according to the current pattern. This still isn't ideal for responsiveness, because SlideList currently only switches between showing all items and showing only 1 item, so on intermediate screen widths the elements are still squished.
I have a followup PR (#239) to expand/collapse SlideList based on the width of the element rather than the overall screen size, which will fix the above problem. I just need to fix the tests on that.
Fixes #169 
| 📸 |  |
| 📕 | ![Screenshot 2025-02-10 at 07 45 56](https://github.com/user-attachments/assets/2f984892-c3e5-494a-8f22-4efd72c7647c)|
| | ![Screenshot 2025-02-10 at 07 46 06](https://github.com/user-attachments/assets/09ead6c7-86b0-4e47-a142-306f4853c852)|
| 🖥️ | …
=> Use SlideList for ValuesSection and BeliefsSection

apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap, apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap, apps/website-25/src/components/homepage/CommunitySection/__snapshots__/GovernanceProjects.test.tsx.snap, apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, apps/website-25/src/globals.css, libraries/ui/src/Card.tsx, libraries/ui/src/__snapshots__/Card.test.tsx.snap, libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
More typography fixes
- Body text was too small compared to mocks. Updating to text-size-sm. Left a note in the Design System Figma board that this does not look accurate to mock usage.
```
Time:    2.61s 
```
=> More typography fixes

apps/website-25/.env.local.template, apps/website-25/src/components/Analytics.tsx, apps/website-25/src/lib/analytics.ts
Add `analytics.isDebugModeEnabled` for conveniently testing Google Analytics locally.
Follow-up to #285.
```
Time:    5.099s 
```
=> Add `analytics.isDebugModeEnabled()` for testing analytics

libraries/ui/src/CourseCard.tsx
Course card should not open in external URL
Fixes #281 
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
```
@bluedot/website-25:test:    Start at  09:18:55
@bluedot/website-25:test:    Duration  3.11s (transform 442ms, setup 0ms, collect 11.21s, tests 388ms, environment 5.09s, prepare 2.18s)
```
=> Course card should not open in external URL

apps/availability/next-env.d.ts, apps/login-account-proxy/next-env.d.ts, apps/meet/next-env.d.ts
When running `npx turbo build lint test`, discovered these hadn't been updated way back when we updated Next.js (#25). Doing this chore now.
=> chore: Boring next-env.d.ts updates

.github/pull_request_template.md
These are run with CI automatically (where anyone can see the logs), and enforced in the merge requirements. Getting humans to run the task and copy over logs manually is therefore unnecessary.
=> devex: Remove running automated tests from PR template

apps/website-25/src/components/homepage/CourseSection.tsx, apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, apps/website-25/src/pages/_app.tsx, apps/website-25/tsconfig.json, libraries/ui/src/CourseCard.stories.tsx, libraries/ui/src/CourseCard.test.tsx, libraries/ui/src/CourseCard.tsx, libraries/ui/src/Footer.tsx, libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap, libraries/ui/src/__snapshots__/Footer.test.tsx.snap, libraries/ui/src/constants.ts, libraries/ui/src/index.ts
The list of courses is currently duplicated in a few places and is inconsistent with things like property naming, and which courses are included. This PR puts them in one place in ui (because they're currently hardcoded in the Footer, which is in ui).
Fixes #308
There are several issues open for courses missing in different places, and the code seems duplicated and inconsistent about handling these without good reason.
This might not be the right list of courses to be going ahead with in the near future, but at least this gives us one place where we can update it.
Maybe in the future this moves to TinaCMS, or links in with the platform directly, so this isn't necessary. But this is a step closer to having less chaos about what courses we list.
The list of courses is now quite big in the …
=> website+ui: Fix missing courses in a few places

apps/website-25/src/components/homepage/__snapshots__/FAQSection.test.tsx.snap, libraries/ui/src/Collapsible.tsx, libraries/ui/src/__snapshots__/Collapsible.test.tsx.snap
Collapsible: Improve text target size, simplify margin and padding stacking. This makes it easier to hit the click target when navigating, and reduces the complexity of using these Collapisble components elsewhere.
Fixes #288
No visual changes
=> ui: Collapsible: Improve text target size, simplify margin and padding stacking

libraries/ui/src/Collapsible.tsx, libraries/ui/src/__snapshots__/Collapsible.test.tsx.snap
Use the webkit specific prefix for managing the marker on Safari
Fixes #349
eugh classic Safari not being standards compliant :(
=> website: Fix Safari collapsible marker

apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap, apps/website-25/src/components/about/__snapshots__/BeliefsSection.test.tsx.snap, apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap, apps/website-25/src/components/careers/__snapshots__/ValuesSection.test.tsx.snap, apps/website-25/src/components/homepage/CommunitySection/__snapshots__/CommunityValuesSection.test.tsx.snap, apps/website-25/src/components/homepage/CommunitySection/__snapshots__/GovernanceProjects.test.tsx.snap, apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap, apps/website-25/src/components/homepage/CommunitySection/__snapshots__/ValuesSection.test.tsx.snap, apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, apps/website-25/src/components/homepage/__snapshots__/FAQSection.test.tsx.snap, libraries/ui/src/SlideList.tsx, libraries/ui/src/shared.css
Hide native scrollbar for SlideList
Fixes #353 
- Use CSS to visually hide native scrollbars as we have a custom scroll bar implemented
- Also reorged the Tailwind utilities in alphabetical order
I noticed SlideList Storybook has broken; opened a ticket to triage a fix for next sprint: 
| 📸 |  |
| 📕 | https://github.com/user-attachments/assets/f21ca7ea-6e24-4538-adea-87516a666737 |
| 🖥️ |  https://github.com/user-attachments/assets/82d1da73-46ba-4665-bed9-f2ff05a5d026 |
| 📱  | <img width="390" alt="image" src="https://github.com/user-attachments/assets/4e61d1d1-dff2-4413-8ae2-43a318770c88" /> |
```
Cached:    2 cached, 7 total
Time:    3.899s 
```
=> Hide native scrollbar for SlideList

apps/website-proxy/src/nginx.template.conf
Include additional new website resources. I've verified these don't appear to be used by the old website, and the key pages e.g. `/blog/` render correctly.
This is needed to have the fonts and images etc. load for the new website.
=> website-proxy: Include additional new website resources

apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap, apps/website-25/src/components/careers/CareersSection.tsx, apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap, apps/website-25/src/pages/about.tsx, apps/website-25/src/pages/careers.tsx, apps/website-25/src/pages/careers/ai-safety-teaching-fellow.tsx, apps/website-25/src/pages/careers/swe-contractor.tsx, apps/website-25/src/pages/index.tsx, apps/website-25/src/pages/privacy-policy.tsx, libraries/ui/src/HeroSection.stories.tsx, libraries/ui/src/HeroSection.test.tsx, libraries/ui/src/HeroSection.tsx, libraries/ui/src/__snapshots__/HeroSection.test.tsx.snap, libraries/ui/src/index.ts
Adds CTAs to HeroSections, cleans up hero-related components
Fixes #343, fixes #310, fixes #301
- Changed Hero-related components to be composable
- Added CTA Hero component
- Used this to simplify the job posting pages
- Added CTAs to the various pages that are missing them
- Updated the padding so it's more similar to the Figma designs
- Added storybook stories
=> website: Add CTA support to HeroSection, add CTAs

.github/workflows/ci_cd.yaml, .github/workflows/create-paths-filter.js, apps/infra/README.md
Update GitHub Actions configuration to discover apps, rather than having to specify them explicitly
At the moment, adding a new app requires adding a block in the ci_cd.yaml for GitHub Actions.
We want to be able to easily create new apps to quickly deploy experiments etc, so the easier the process is the better. This part is also particularly fiddly so it'd be good to cut it out completely.
I've updatd the ci_cd.yaml to loops over all the apps that need deploying, and then deploys the ones that need deploying. I've also taken the opportunity to properly get the dependencies for the apps, e.g. so a change in libraries/ui results in website deploying, as one might expect (Currently apps will deploy only if you edit files within their app folder, and not their dependencies - although they …
=> infra: Avoiding having to manually add apps to cd_cd config

apps/website-proxy/src/nginx.template.conf
This is in preparation for phased deployment where we only add the about page on Monday, and then the other pages once we have confirmed that works.
Also see https://www.notion.so/bluedot-impact/plan-for-deployment-on-Monday-199f8e69035380839ab9d169f4a740ff
=> website-proxy: Disable all routes

apps/website-25/src/globals.css
Update animation to offset to 100% by the end, so that it lines up with the jump back to where it was. Also doubled the duration to account for the double travel so it moves the same speed.
Fixes #416
=> website: Fix infinite scroll to go all the way around

libraries/ui/src/default-config/tailwind.css
Update the syntax for utility classes for Tailwind 4, which enables them to work with the Tailwind prefixes e.g. `lg:container-lined`.
Fixes #411
I followed these steps in the Tailwind v4 upgrade guide: https://tailwindcss.com/docs/upgrade-guide#adding-custom-utilities, which I missed in #355. I also went through all the other steps and double-checked these were applied or not relevant to our app, and I think this is the only bit we missed.
=> ui: Fix utility classes for Tailwind 4

apps/meet/package.json, package-lock.json
Minor dep tidy up. This also means we shouldn't have Tailwind 3 floating around any more outside the eslint package, which should make the Tailwind intellisense VS code extension happier.
=> meet: Remove unused tailwindcss-scoped-preflight package

.github/workflows/ci_cd.yaml, .github/workflows/get-app-paths.js
Moves the skip-duplicate-actions check to the CD flow, which _should_ reduce the number of deploy attempts. This will in turn reduce the number of failed workflows as a result of Vultr 504 errors.
=> cd: Reduce unnecessary CD runs

.github/workflows/ci_cd.yaml, .github/workflows/website_deploy_production.yaml, README.md, apps/availability/package.json, apps/backend/package.json, apps/bubble-proxy/package.json, apps/frontend-example/package.json, apps/infra/README.md, apps/infra/package.json, apps/infra/src/k8s/serviceDefinitions.ts, apps/login-account-proxy/package.json, apps/login/package.json, apps/meet/package.json, apps/miniextensions-proxy/package.json, apps/posthog-proxy/package.json, apps/storybook/package.json, apps/website-25/.env.production.template, apps/website-25/.env.staging.template, apps/website-25/package.json, apps/website-proxy/package.json, libraries/docker-scripts/README.md, libraries/docker-scripts/src/index.js, libraries/docker-scripts/src/multistage/deploy-production.sh, libraries/docker-scripts/src/multistage/deploy-staging.sh
* Add `bluedot-website-25-production`-container
* Introduce *multistage* deployment workflow for `website-25`
Fixes #58, but will require a few follow ups to actually the switch to the new production environment. See `### Rollout` ⬇️.
* **staging** Push to `master` triggers a deploy to `bluedot-website-25`. _This is the current behavior._
* **production** Push a `website-release*`-tag to `master` to trigger a deploy to `bluedot-website-25-production`. 
We can even choose to make it a convention to create `GitHub Releases` for production deploys.
That way we can add a quick description of the release & keep a transparent history of releases.
ℹ️ I prepared a branch implementing the steps outlined above over at https://github.com/janraasch/bluedot/pull/1.
This implementation draws …
=> Add multistage deploy for `website-25`

.github/workflows/ci_cd.yaml
Force deploy of `website-proxy`
See https://github.com/bluedotimpact/bluedot/actions/runs/13433229734/job/37529650860
Will revert this right after.
Following up on #463.
=> Force deploy of `website-proxy`

apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap, apps/website-25/src/components/careers/CareersSection.tsx, apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap, apps/website-25/src/components/homepage/StorySection.tsx, apps/website-25/src/lib/routes.ts, apps/website-25/src/pages/_app.tsx, apps/website-25/src/pages/about.tsx, apps/website-25/src/pages/careers.tsx, apps/website-25/src/pages/careers/ai-safety-teaching-fellow.tsx, apps/website-25/src/pages/careers/swe-contractor.tsx, apps/website-25/src/pages/index.tsx, apps/website-25/src/pages/privacy-policy.tsx, libraries/ui/src/Breadcrumbs.stories.tsx, libraries/ui/src/Breadcrumbs.test.tsx, libraries/ui/src/Breadcrumbs.tsx, libraries/ui/src/CookieBanner.test.tsx, libraries/ui/src/CookieBanner.tsx, libraries/ui/src/__snapshots__/Breadcrumbs.test.tsx.snap, libraries/ui/src/__snapshots__/CookieBanner.test.tsx.snap, libraries/ui/src/index.ts, libraries/ui/src/utils.ts
1. Added breadcrumbs component
2. Refactored all internal navigation to use predefined route urls and titles. The idea here is to make it easier to maintain consistency between the tab name, breadcrumb title, and any other places the title might appear
Fixes #397 
| 📸 |  |
| 📕 | ![Screenshot 2025-02-19 at 10 27 36](https://github.com/user-attachments/assets/dfd1b17a-f370-45ef-82a9-f2388f02222a) |
| 🖥️ | ![Screenshot 2025-02-19 at 10 28 00](https://github.com/user-attachments/assets/4f307da0-b0a6-427a-bd8e-fcd42d965310) |
| 📱  | ![Screenshot 2025-02-19 at 10 28 25](https://github.com/user-attachments/assets/a10620b1-60f6-44db-aed1-d072bf4a461d) |
```
Cached:    4 cached, 7 total
Time:    4.765s
```
=> Add breadcrumbs component

apps/website-25/.env.local.template
Use *staging* `GA_MEASUREMENT_ID` to `.env.locale.template`.
For PostHog we already have the dev/testing key on `.env.locale.template`
Following up on #460
=> website-25: Add `staging` GA key to `.env.locale.template`

apps/website-25/Dockerfile
Trigger `website-25` deploy to `staging`.
Previous deployment timed out: https://github.com/bluedotimpact/bluedot/actions/runs/13434067582/job/37532464968.
Follow up on #460.
=> Trigger `website-25` deploy to `staging`

.github/workflows/ci_cd.yaml, apps/website-25/Dockerfile
Force `website-25` deploy to `staging`.
Follow up on https://github.com/bluedotimpact/bluedot/pull/469.
=> Force `website-25` deploy to `staging`

.github/workflows/ci_cd.yaml
This workflow runs on pull requests, which then means when pushing to master this action thinks a duplicate run has passed successfully.
Disabling this _should_ result in fkirc/skip-duplicate-actions using the backtracking algorithm detailed in [their README](https://github.com/fkirc/skip-duplicate-actions/), which I think should be doing what we want.
Fixes (maybe) #472
=> cd: set skip_after_successful_duplicate to false

apps/website-proxy/src/nginx.template.conf
Redirect `careers` to `join-the-team` & serve job postings from `website-25`
Following up on #486
⚠️ Wait for #486 to be released to `production` before merging ⚠️
=> website-proxy: redirect `careers` to `join-us` & serve job postings from `website-25`

apps/website-25/src/components/homepage/CommunitySection/CommunityValuesSection.stories.tsx, apps/website-25/src/components/homepage/CommunitySection/ProjectsSubSection.stories.tsx, apps/website-25/src/components/homepage/CommunitySection/TestimonialSection.stories.tsx
Unite `website-25` stories under common `Website` namespace 🧹.
I stumbled upon this as part of #252.
**Goal:** Have one namespace per `app` / `library`.
```
Tasks:    9 successful, 9 total
Cached:    8 cached, 9 total
Time:    3.802s 
```
=> storybook: Move `Homepage` stories to `Website` namespace

apps/website-proxy/src/nginx.template.conf
Add 301 permanent redirect from `www.bluedot.org` to `bluedot.org`
Fixes #487
I've verified my solution through Claude and cross-referenced it with [this gist](https://gist.github.com/EmranAhmed/946a74c0331832040844) 😇, though I couldn't test the `nginx.template.conf` locally.
📸 **No visual changes**
```
Tasks:    9 successful, 9 total
Cached:    4 cached, 9 total
Time:    5.404s 
```
=> website-proxy: 301 redirect `www.bluedot.org` to `bluedot.org`

.vscode/extensions.json, apps/storybook/.storybook/main.ts, apps/storybook/src/GettingStarted.mdx
Add "Design System" page to Storybook for improved documentation and reference.
Fixes #252.
* Added the "Design System" page on the "Getting Started" section, making it the first thing visible when opening Storybook.
* This provides the foundation for our design system documentation.
* The documentation will evolve alongside our design system as it matures.
```
Tasks:    12 successful, 12 total
Cached:    0 cached, 12 total
Time:    10.326s 
```
=> storybook: Add "Design System" page

apps/infra/src/k8s/serviceDefinitions.ts
Fixes #474 
I thought about setting up a redirect from `website-25` -> `website-25-staging`, but given the only people using it are a few devs a Slack message probably ought to do the trick? Less complex and less to maintain.
=> website-25: Updating staging URL to `website-25-staging.k8s.bluedot.org`

apps/room/public/display/setup/kiosk/kiosk.service, apps/room/public/display/setup/kiosk/kiosk.sh, libraries/ui/src/utils/makeMakeApiRoute.ts
Two key changes:
1. Improve the kiosk script. The main change here is using firefox instead of Google Chrome, because it works better with higher-res webcams. I also added some environment variables to the systemd script that enables access to D-Bus, so firefox can access all the microphone/webcam devices.
2. Prevent API recursion depth errors, by modifying makeMakeApiRoute. On each request, we were modifying the requestBody schema. Because this was captured in the higher level closure it was being nested, until eventually checking it was no longer feasible and we got errors. This fixes the problem by not modifying the opts object. Should have listened to the ESLint warning in the first place 🤦
=> room: Reliability and performance improvements

apps/course-demos/src/pages/generate-react-component.tsx
This doesn't work reliably, and the touch events sometimes are weird when embedded in an iframe on mobile.
=> course-demos: Remove whiteboard preset

apps/course-demos/src/components/ShareButton.tsx
Auto means the scrollbars only show when necessary, and limiting it to x prevents an unnecessary up/down scrollbar that appears on Windows (by default, macOS hides the scrollbar when using a trackpad even with overflow scroll).
=> course-demos: Improve sharing url view on Windows

apps/website-25/src/components/lander/LandingPageBase.tsx
Before:
https://github.com/user-attachments/assets/ab48330d-f28b-489a-b1a7-f0d430674847
After:
https://github.com/user-attachments/assets/32155753-a7bc-459d-939e-cc8694a62171
(title font changes are unrelated, ignore - that's just because I was also working on #541)
=> landing: Fix button/image interaction bug in 'you're in good hands' section

apps/website-25/src/components/lander/getCtaUrl.ts
Pass through parameters to miniextensions, so they can be recorded in Airtable
For example, utm_content becomes prefill_utm_content.
=> website: landing: Pass through other params to miniextension prefills

libraries/eslint-config/package.json, package-lock.json
devex: Fix package.json for eslint-config linking to eslint-plugin-custom
This was causing mysterious npm errors when installing packages, but only sometimes, such as:
```
npm error Cannot read properties of undefined (reading 'extraneous')
```
The package name for our custom eslint plugin was wrong in eslint-config's package.json. I figured this out by editing the NPM source code to print out more details of the error, and it was consistently when resolving the @bluedot/eslint-config package. I'm fairly certain this was the cause of the problem, but I can't be certain - we'll see if the bug reappears.
=> devex: Fix package.json for eslint-config linking to eslint-plugin-custom

apps/website-25/src/lib/routes.ts, apps/website-25/src/pages/courses.tsx, apps/website-25/src/pages/courses/future-of-ai.tsx, apps/website-25/src/pages/courses/future-of-ai/index.tsx, apps/website-25/src/pages/courses/future-of-ai/units/1.tsx
Introduce Courses and Future of AI skeleton pages
#584 
Add /courses and /courses/future-of-ai (These should cause no namespacing issues as http://bluedot.org/courses and https://bluedot.org/courses/future-of-ai/ do not currently exist). Include Unit 1 as example Unit course under /courses/future-of-ai/unit/1
This follows the site architecture and meta tag recommendations from our [SEO Audit](https://docs.google.com/document/d/1zswDry2NWi0qmSY_8SBj3hTClL6En0g27D_WLibAIzE/edit?tab=t.0#bookmark=kix.s5b55k1xbk3t)
```
```
=> Introduce Courses and Future of AI skeleton pages

apps/website-25/src/__tests__/pages/__snapshots__/404.test.tsx.snap, apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website-25/src/__tests__/pages/__snapshots__/join-us.test.tsx.snap, apps/website-25/src/components/courses/UnitLayout.tsx, apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap, apps/website-25/src/pages/courses/future-of-ai/units/1.tsx, libraries/ui/src/Breadcrumbs.tsx, libraries/ui/src/__snapshots__/Breadcrumbs.test.tsx.snap
Sticky breadcrumbs on Unit pages
Fixes #595 
- MVP Sticky breadcrumbs on course content scroll
- Ideally, both Breadcrumbs and SideBar should stay sticky while course content is scrolled. See references: Ex: https://www.acnestudios.com/uk/en/layered-print-t-shirt-dark-mauve/AL0454-CJD.html?g=man , https://jsfiddle.net/dibdab/1xsv8v35/3/
- Timeboxing for efficiency 
https://github.com/user-attachments/assets/4c70d1df-2a38-472e-adea-e6ad27f827d2
https://github.com/user-attachments/assets/90ec96be-8b9a-4a6e-9a64-ab58e7e001e8
```
```
=> Sticky breadcrumbs on Unit pages

apps/website-25/package.json, apps/website-25/src/components/courses/UnitLayout.test.tsx, apps/website-25/src/components/courses/UnitLayout.tsx, apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap, apps/website-25/src/globals.css, apps/website-25/src/pages/courses/future-of-ai/units/1.tsx, apps/website-25/src/pages/courses/future-of-ai/units/2.tsx, apps/website-25/src/pages/courses/future-of-ai/units/3.tsx, apps/website-25/src/pages/courses/future-of-ai/units/4.tsx
Handle markdown text in UnitLayout
fixes #593 
- Because of the global.css base layer styling, we can consume markdown relatively simply
- Use [react-markdown](https://www.npmjs.com/package/react-markdown) package
- Some global.css styling tweaks to accomodate
- This solution keeps us in sync with global styling for a more scalable maintenance solution 
```
```
=> Handle markdown text in UnitLayout

apps/website-25/src/components/courses/SideBar.tsx, apps/website-25/src/components/courses/__snapshots__/SideBar.test.tsx.snap, apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
Stronger current unit indicator in sidebar
```
```
=> Stronger current unit indicator in sidebar

apps/website-25/package.json, apps/website-25/src/components/courses/Greeting.stories.tsx, apps/website-25/src/components/courses/Greeting.tsx, apps/website-25/src/components/courses/MarkdownExtendedRenderer.stories.tsx, apps/website-25/src/components/courses/MarkdownExtendedRenderer.test.tsx, apps/website-25/src/components/courses/MarkdownExtendedRenderer.tsx, apps/website-25/src/components/courses/UnitLayout.tsx, apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap, package-lock.json
I think in #596 we added Markdown rendering, but not Markdown extended (MDX).
Using MDX allows us to embed components in the content, enabling things like embedded video content, demos and exercises.
Fixes #593. Also likely to be very helpful for #585
=> website: Add MDX rendering for course content

apps/website-25/src/components/courses/Callout.stories.tsx, apps/website-25/src/components/courses/Callout.tsx, apps/website-25/src/components/courses/Embed.stories.tsx, apps/website-25/src/components/courses/Embed.tsx, apps/website-25/src/components/courses/MarkdownExtendedRenderer.stories.tsx, apps/website-25/src/components/courses/MarkdownExtendedRenderer.tsx, apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap, apps/website-25/src/components/homepage/__snapshots__/FAQSection.test.tsx.snap, libraries/ui/src/Collapsible.tsx, libraries/ui/src/__snapshots__/Collapsible.test.tsx.snap
Add components:
- `Embed` for iframe content, like YouTube videos, demos, etc.
- `Callout` for bonus content
Part of #616, may also help with #585
=> website: Add Embed and Callout components

apps/website-25/src/components/courses/Congratulations.stories.tsx, apps/website-25/src/components/courses/Congratulations.test.tsx, apps/website-25/src/components/courses/Congratulations.tsx, apps/website-25/src/components/courses/SocialShare.stories.tsx, apps/website-25/src/components/courses/SocialShare.test.tsx, apps/website-25/src/components/courses/SocialShare.tsx, apps/website-25/src/components/courses/UnitLayout.tsx, apps/website-25/src/components/courses/__snapshots__/Congratulations.test.tsx.snap, apps/website-25/src/components/courses/__snapshots__/SocialShare.test.tsx.snap, apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
Bug fix Congratulations and SocialShare
- Fix SocialShare URL construction to include base off of dynamic coursePath slugs
- Update a default text copy
- Will need to QA this once the URLs are actually available
```
```
=> Bug fix Congratulations and SocialShare

apps/website-25/src/components/courses/Congratulations.tsx, apps/website-25/src/pages/profile.tsx
Basic profile page UI
Resolves #575 
- Simple course UI for account details and course progress
- Very bare-bones for an initial MVP
- Should update to include links to continue course, course progression, and maybe a more personalized social share to profile page.
- More robust testing, e.g. on SocialShare links w/ referral code working
- We will also need to update Nav bar, likely for a dropdown to take someone to Profile, Help, or Logout
```
```
=> Basic profile page UI

apps/website-25/src/components/courses/SocialShare.tsx, apps/website-25/src/components/courses/__snapshots__/Congratulations.test.tsx.snap, apps/website-25/src/components/courses/__snapshots__/SocialShare.test.tsx.snap, apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap, apps/website-25/src/pages/api/users/me.ts, apps/website-25/src/pages/profile.tsx
Returns coursePath from the `/api/me` route, and uses it to link to course if it is in-progress.
#646 
This doesn't fully resolve the ticket, still to do:
- Making the referral flow work end to end (currently it doesn't) and adding a test for this
The only visual change is adding the "Continue" button:
| 📸 |  |
| 📕 |  |
| 🖥️ | ![Screenshot 2025-04-15 at 11 25 06](https://github.com/user-attachments/assets/c106424a-edae-4b29-98c6-6f432e92eb65) |
| 📱  | ![Screenshot 2025-04-15 at 11 25 21](https://github.com/user-attachments/assets/694e456b-0bf4-42d0-aa12-33603d85bb7a) |
```
Tasks:    13 successful, 13 total
Cached:    1 cached, 13 total
Time:    24.451s
```
=> Link to course from profile page

apps/website-25/src/components/Nav.tsx, apps/website-25/src/components/__snapshots__/Nav.test.tsx.snap
Add a link to our luma events page to the nav bar
Related to #655
=> website: Add events to nav

apps/website-25/package.json, apps/website-25/src/components/courses/exercises/Exercise.tsx, apps/website-25/src/components/courses/exercises/FreeTextResponse.stories.tsx, apps/website-25/src/components/courses/exercises/FreeTextResponse.test.tsx, apps/website-25/src/components/courses/exercises/FreeTextResponse.tsx, apps/website-25/src/components/courses/exercises/MultipleChoice.stories.tsx, apps/website-25/src/components/courses/exercises/MultipleChoice.test.tsx, apps/website-25/src/components/courses/exercises/MultipleChoice.tsx, apps/website-25/src/components/courses/exercises/__snapshots__/FreeTextResponse.test.tsx.snap, apps/website-25/src/components/courses/exercises/__snapshots__/MultipleChoice.test.tsx.snap, apps/website-25/src/lib/api/db/tables.ts, apps/website-25/src/pages/api/courses/exercises/[exerciseId].ts, apps/website-25/src/pages/api/courses/exercises/[exerciseId]/index.ts, apps/website-25/src/pages/api/courses/exercises/[exerciseId]/response.ts, package-lock.json
Updating Exercise, FreeTextResponse, and MultipleChoice to handle saving, updating, and rendering saved user responses
Fixes #562 
- New APIs:
- GET /api/courses/exercises/${exerciseId} – does not require auth, returns exercise details
- GET /api/courses/exercises/${exerciseId}/response – requires auth, returns saved exercise responses
- PUT /api/courses/exercises/${exerciseId}/response – requires auth, upsert exercise with new submitted state
- Exercise handles API methods and passes a callback to FreeTextResponse and MultipleChoice
- Use react-hook-form to help handle form updates in FreeTextResponse and MultipleChoice
https://github.com/user-attachments/assets/5d3748d7-ddb5-4fc7-a408-0e54357ae378
https://github.com/user-attachments/assets/041ef8a3-0e75-49e7-ab74-dd79424d77aa
=> Exercise API get and put handling

apps/website-25/src/components/courses/StarRating.tsx, apps/website-25/src/components/courses/__snapshots__/StarRating.test.tsx.snap, apps/website-25/src/components/courses/__snapshots__/UnitFeedback.test.tsx.snap
Make stars more delightful to use:
- fix padding so scrolling your mouse over them doesn't result in jumping between values
- add animations so they feel more 'springy' and fun to use
Fixes #668 
These are really fun to use now
https://github.com/user-attachments/assets/f88261d5-3f94-4dc0-91b8-dffc79bc13b0
=> website-25: Improve stars component

apps/website-25/src/components/Nav.tsx, apps/website-25/src/components/__snapshots__/Nav.test.tsx.snap
website-25: Fix explore menu in Nav on desktop
The desktop explore panel was incorrectly nested inside the mobile panel. This PR moves it out of the mobile panel, so it displays properly on desktop. The `hidden lg:flex` already stops it being shown on mobile.
Fixes #673
=> website-25: Fix explore menu in Nav on desktop

apps/website-25/src/components/courses/MarkdownExtendedRenderer.tsx, apps/website-25/src/components/lander/ClassicHero.tsx, apps/website-25/src/components/lander/LandingPageBase.tsx, apps/website-25/src/pages/courses/[courseSlug]/index.tsx
Add more usable course landing pages
For future of AI, this reuses our classic landing page (which performed best at converting users in our most recent tests).
For other courses, this renders the description as markdown and lists the units. This was 80% done already, and I'm not going to bother polishing this right now because (1) it doesn't look too bad, (2) it's not planned to go live soon - we're going to redirect to the old course hub for the resource-list courses for now.
Fixes #654
https://github.com/user-attachments/assets/3e6f730a-2f43-4048-9699-e41a0522d4a4
| Mobile: FOAI | Mobile: Other |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/64e9abd2-be85-4164-8494-b09fac2e254b) | ![image](https://github.com/user-attachments/assets/89fe05c9-688f-4fda-a6c9-cf0 …
=> website-25: Add more usable course landing pages

apps/website-25/src/__tests__/pages/courses/[courseSlug]/units/[unitId].test.tsx, apps/website-25/src/pages/courses/[courseSlug]/units/[unitId].tsx
website-25: Fix unit page indexing
Previously this broke if units were not 1-indexed, or not continuous. This could be seen on some of the existing courses where unit 0 is an icebreaker session. e.g.:
- unit 0 doesn't render properly at all
- unit 1 renders the content for unit 0
- unit 2 renders the content for unit 1
- ...
This PR improves the unit number handling logic to be more robust.
Fixes #676
Unit 0 renders properly now 🎉:
=> website-25: Fix unit page indexing

apps/website-25/src/components/Nav.stories.tsx, libraries/ui/src/index.ts, libraries/ui/src/utils/storybook.ts
Adds `loggedOutStory()` and `loggedInStory()` utils which can be spread into the story params.
I have applied this to the `Nav` stories, all the others require additional mocking of API calls which is more involved to fix. I have made another followup ticket for that (#687) (which I will claim and start on, seeing as getting all the stories working was the intent of this ticket)
Fixes #650
| 📸 |  |
| 📕 | ![Screenshot 2025-04-23 at 12 48 34](https://github.com/user-attachments/assets/7ecc7f50-ed00-4176-afbe-9c987017a0b2) |
| | ![Screenshot 2025-04-23 at 12 48 41](https://github.com/user-attachments/assets/a1e99d56-ecd7-48f7-9a68-169066b906d7) |
| 🖥️ |  |
| 📱  |  |
```
Tasks:    13 successful, 13 total
Cached:    9 cached, 13 total
Time:    19.086s
```
=> Add utils for mocking login state in stories

apps/infra/src/vultr/vke.ts
Bump from 2 cores and 4GB RAM -> 4 cores and 16GB RAM.
Possibly we should go memory optimised (e.g. 2 cores and 16GB for $80/month) - memory is usually our main bottleneck. But for the sake of being prepared to scale am going with 4 cores. And it's all quite cheap.
Pricing $40/month -> $120/month. Bare metal is cheap :D
Also see https://www.vultr.com/pricing/#optimized-cloud-compute
=> infra: Bump k8s node size

apps/website-25/src/components/courses/Embed.tsx
For YouTube videos, we want a 16:9 aspect ratio to reduce [letterboxing](https://en.wikipedia.org/wiki/Letterboxing_(filming)).
In #643 I think we tweaked the embed styles to change the height, but moved the height tag from the !isYoutube condition so it also applied to YouTube videos. This PR fixes the behaviour by setting the height (rather than aspect ratio) only when it's not YouTube.
| Before | After |
| - | - |
| ![image](https://github.com/user-attachments/assets/f7dbee66-4038-43ef-bea4-41dc392ed691) | ![image](https://github.com/user-attachments/assets/55411a73-6837-40d2-b3a9-77524f7689c4) |
=> website-25: Embed: Fix YouTube video sizing

apps/website-25/src/globals.css
Increase markdown font size and line height for readability
- Issue flag: https://bluedotimpact.slack.com/archives/C08LQKWBX9B/p1745420887283019
- https://pimpmytype.com/line-length-line-height/
- Styles apply only to MarkdownExtendedRenderer
- In the future, UXD should come up with a more robust overall layout + typography solution
=> Increase markdown font size and line height for readability

apps/website-25/src/components/__snapshots__/Nav.test.tsx.snap, libraries/ui/src/IconButton.tsx
Update icons for Safari browsers
=> Update icons for Safari browsers

.gitignore, apps/app-template/src/pages/login/index.tsx, apps/app-template/src/pages/login/oauth-callback.tsx, apps/frontend-example/package.json, apps/frontend-example/src/pages/login/index.tsx, apps/frontend-example/src/pages/login/oauth-callback.tsx, apps/room/src/pages/login/index.tsx, apps/room/src/pages/login/oauth-callback.tsx, apps/website-25/src/components/Nav.test.tsx, apps/website-25/src/pages/login/index.tsx, apps/website-25/src/pages/login/oauth-callback.tsx, libraries/ui/README.md, libraries/ui/package.json, libraries/ui/src/legacy/Login.tsx, libraries/ui/src/utils/auth.test.tsx, libraries/ui/src/utils/auth.tsx, libraries/ui/src/utils/storybook.ts, package-lock.json
Adds refresh token logic to auth.tsx, enabling long-lived and secure sessions.
Fixes #694
Uses OidcClient instead of UserManager so we have more control over the refreshing logic - with the built-in refreshing of UserManager it's not clear how we get notified of changes to the token, and we can't hydrate the refresh token from localstorage AFAIK.
=> ui(auth): add refresh token logic

libraries/ui/src/utils/auth.test.tsx
`runOnlyPendingTimersAsync` has weird behaviour that caused an infinite timer loop. Using the vitest docs recommended `advanceTimersByTimeAsync` fixes this for me.
Fixes #713
=> Fix flakey auth test

apps/website-25/src/lib/api/db/tables.ts, apps/website-25/src/pages/api/users/me.ts, apps/website-25/src/pages/login/oauth-callback.tsx, apps/website-25/src/pages/profile.tsx, libraries/ui/src/legacy/Login.tsx
website-25: Create new users in Airtable when logging in for the first time
Fixes #696
Mostly a backend change: when we try to get the current user, we create one in Airtable if one does not exist. Then we call this endpoint when logging in (as part of oauth callback) to ensure the user exists in Airtable if they go through the login flow.
Tested locally by creating a new user.
Also put in some groundwork for updating the user with a PATCH, which will be useful for the user to update their name etc. but not used yet.
=> website-25: Create new users in Airtable when logging in for the first time

apps/app-template/.env.local.template, apps/app-template/package.json, apps/availability/.env.local.template, apps/availability/package.json, apps/course-demos/.env.local.template, apps/course-demos/package.json, apps/frontend-example/.env.local.template, apps/frontend-example/package.json, apps/login-account-proxy/.env.local.template, apps/login-account-proxy/package.json, apps/meet/.env.local.template, apps/meet/package.json, apps/room/.env.local.template, apps/room/package.json, apps/website-25/.env.local.template, apps/website-25/package.json, package-lock.json
Most apps create `.env.local` automatically if it doesn't exist on `postinstall`, but not all. This PR makes it consistent across all apps.
Also the Slack token isn't really required - shoving 'IGNORE_SLACK_ALERTS' as the API token will generally cause it to fail quietly which is fine locally. I've filled it in like this to make getting started easier.
=> devex: Make setup of .env.local easier

apps/website-25/.env.local.template, apps/website-25/src/pages/_app.tsx
- Init posthog in a useEffect hook, in line with PostHog docs to prevent random extra re-inits that cause errors
- Fix persistence setting so we are ePrivacy regs compliant - default to storing in memory (rather than a cookie) until acceptance
- Fix debug mode loading, but disable it by default to reduce log noise
- Remove unnecessary logs
=> website-25: Clean up PostHog setup

apps/website-25/src/components/courses/MarkdownExtendedRenderer.tsx, apps/website-25/src/components/courses/UnitFeedback.tsx, apps/website-25/src/components/courses/UnitLayout.tsx, apps/website-25/src/components/courses/__snapshots__/UnitFeedback.test.tsx.snap, apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
Fixes various issues tracked in Slack (have reacted ✅ on them):
- Make UnitFeedback '1 min' label not look like a link
- Fix content width being inconsistent with e.g. feedback / congratulations window
- Fix next/prev unit buttons
https://github.com/user-attachments/assets/26a29ab9-9081-4ab3-9234-1589259f8bc5
=> website-25: Address Slack feedback

libraries/ui/src/legacy/Login.test.tsx, libraries/ui/src/legacy/Login.tsx
Fix Login redirect logic
- Builds off of https://github.com/bluedotimpact/bluedot/pull/718 and https://github.com/bluedotimpact/bluedot/pull/724
- Started adding Login tests but had trouble with Oicd mocks so time boxed and am addressing this separately in [Add tests to Login.tsx](https://github.com/bluedotimpact/bluedot/issues/720) 
https://github.com/user-attachments/assets/4918a0aa-0c6c-4d08-9313-424b60e1db1d
https://github.com/user-attachments/assets/9cc1bdbb-1207-4e27-86a9-299825bee8c4
https://github.com/user-attachments/assets/6df77d1d-f687-4797-abb0-996f103fbdad
=> Fix Login redirect logic

apps/website-25/src/components/courses/MarkdownExtendedRenderer.tsx, apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
https://bluedotimpact.slack.com/archives/C08LQKWBX9B/p1745426786571269
Before:
After:
Also raised upstream: https://github.com/tailwindlabs/tailwindcss-typography/issues/391
=> website-25: Fix heading link font weight

apps/website-25/src/components/courses/exercises/FreeTextResponse.tsx, apps/website-25/src/components/courses/exercises/MultipleChoice.tsx, apps/website-25/src/components/courses/exercises/__snapshots__/FreeTextResponse.test.tsx.snap, apps/website-25/src/components/courses/exercises/__snapshots__/MultipleChoice.test.tsx.snap
=> website-25: Fix exercise heading formatting

apps/website-25/src/components/homepage/HomeHeroContent.tsx, apps/website-25/src/components/homepage/__snapshots__/HomeHeroContent.test.tsx.snap
Reverts bluedotimpact/bluedot#610, to restore the homepage hero animation
Fixes #738 
Fixes #611
Fixes #395
We think this works now after #736
=> Restore "Rive on homepage"

libraries/ui/src/utils/addQueryParam.test.ts, libraries/ui/src/utils/addQueryParam.ts, libraries/ui/src/utils/getQueryParam.test.ts, libraries/ui/src/utils/getQueryParam.ts
- Add handling for empty string keys, which are supported by the search params spec
- Add tests for adding existing keys
- Add tests for getting when there are duplicate keys
=> ui: Add tests and handling for search param edge cases

apps/website-25/src/globals.css
Bug: If you had an overridden style that was a direct descendant of prose it wouldn't get rendered properly, because there is no parent element that isn't set to `not-prose`. (i.e. it required `<prose class="prose"><subcontainer><overridenelement /></subcontainer></prose>`)
This PR fixes the behaviour by allowing the element itself to be a direct descendant of prose, so long as it isn't a .not-prose. (so you can do `<prose class="prose"><overridenelement /</prose>`)
=> website-25: Improve not-prose custom style handling

libraries/ui/src/legacy/Login.tsx
This PR adds th "offline_access" scope parameter to the Keycloak OIDC settings, which is required to obtain refresh tokens that persist beyond user sessions and can be used when the access token expires.
According to the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess), the "offline_access" scope explicitly requests refresh tokens that remain valid even when the user is not present, allowing authentication to be maintained through token expiration.
Without this scope parameter, Keycloak would issue refresh tokens that become invalid once the access token expires, preventing automatic re-authentication on rehydration and forcing users to log in again.
Fixes #751
=> ui(Login): Fix refresh token rehydration after session expiry

apps/website-25/src/components/courses/MarkdownExtendedRenderer.stories.tsx, apps/website-25/src/components/courses/MarkdownExtendedRenderer.test.tsx, apps/website-25/src/components/courses/MarkdownExtendedRenderer.tsx
Unescape MDX attributes in MarkdownExtendedRenderer so that Embeds etc. work with underscores
Also see:
- https://bluedotimpact.slack.com/archives/C08LQKWBX9B/p1745490788274069?thread_ts=1745490689.842799&cid=C08LQKWBX9B
- https://bluedotimpact.slack.com/archives/C08LQKWBX9B/p1745501823046429?thread_ts=1745426786.571269&cid=C08LQKWBX9B
Fixes #750
Implemented a custom remark processor to handle this, so it works for all components without having to have weird logic within those components themselves.
https://github.com/user-attachments/assets/7604ff97-0f40-41ad-9f28-e7004da755bf
=> website-25: Unescape MDX attributes in MarkdownExtendedRenderer so that Embeds etc. work with underscores

apps/website-proxy/src/nginx.template.conf
Add traffic routing for certificates
https://bluedotimpact.slack.com/archives/C04CSNYF5QX/p1745615555418379
- Add traffic routing for anything in /certification route
Wish we could mock out traffic changes somehow?
https://website-staging.k8s.bluedot.org/certification/?id=recg3FUpPCHAxWge5
Confirmed with other's certificates
https://website-staging.k8s.bluedot.org/certification?id=reckcH9U0KVA1jxMe
=> Add traffic routing for certificates

apps/app-template/src/components/ExampleComponent.tsx, apps/app-template/src/pages/authed.tsx, apps/app-template/src/pages/index.tsx, apps/availability/src/pages/form/[slug].tsx, apps/course-demos/src/components/CodeRenderer.tsx, apps/course-demos/src/pages/2018-to-present/index.tsx, apps/course-demos/src/pages/generate-react-component.tsx, apps/course-demos/src/pages/index.tsx, apps/course-demos/src/pages/s/[savedDemoOutputId].tsx, apps/frontend-example/src/components/ErrorPage.tsx, apps/frontend-example/src/pages/adam.tsx, apps/frontend-example/src/pages/authed.tsx, apps/frontend-example/src/pages/dewi.tsx, apps/frontend-example/src/pages/index.tsx, apps/room/src/pages/[roomId].tsx, apps/room/src/pages/display/[roomId].tsx, apps/room/src/pages/index.tsx, apps/website/src/components/Text.tsx, apps/website/src/globals.css, apps/website/src/pages/certification.tsx, libraries/ui/src/Text.tsx, libraries/ui/src/default-config/tailwind.css, libraries/ui/src/index.ts
- Move legacy text components into their own namespace
- Move new text components to ui, also namespaced for now
This will help us in the journey to making sure everything can be migrated onto the new design system components, without missing things.
Related to #749
Confirmed availability and website render normally
=> Move new design system text components into ui

apps/website/public/icons/chevron_blue.svg, apps/website/public/icons/chevron_white.svg, apps/website/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website/src/__tests__/pages/__snapshots__/join-us.test.tsx.snap, apps/website/src/components/about/__snapshots__/JoinUsCta.test.tsx.snap, apps/website/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap, apps/website/src/components/courses/exercises/__snapshots__/FreeTextResponse.test.tsx.snap, apps/website/src/components/courses/exercises/__snapshots__/MultipleChoice.test.tsx.snap, apps/website/src/components/homepage/CommunitySection/__snapshots__/ProjectsSubSection.test.tsx.snap, apps/website/src/components/homepage/__snapshots__/BlogSection.test.tsx.snap, apps/website/src/components/homepage/__snapshots__/StorySection.test.tsx.snap, apps/website/src/components/join-us/__snapshots__/CareersSection.test.tsx.snap, libraries/ui/src/CTALinkOrButton.tsx, libraries/ui/src/__snapshots__/CTALinkOrButton.test.tsx.snap
Previously this assumed all the apps had the icons installed, which is not the case - meaning it couldn't be used across apps easily.
The font awesome icon looks near-identical to the previous icon.
Also withBackChevron was broken on buttons, so I've fixed that.
Part of #749
Before:
After:
=> ui: Fix CTALinkOrButton chevron portability by using FA icons

apps/website/src/__tests__/pages/__snapshots__/404.test.tsx.snap, apps/website/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website/src/__tests__/pages/__snapshots__/join-us.test.tsx.snap, apps/website/src/components/about/HistorySection.tsx, apps/website/src/components/about/__snapshots__/HistorySection.test.tsx.snap, apps/website/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap, apps/website/src/components/homepage/__snapshots__/HomeHeroContent.test.tsx.snap, apps/website/src/globals.css, libraries/ui/src/Footer.tsx, libraries/ui/src/HeroSection.tsx, libraries/ui/src/__snapshots__/Footer.test.tsx.snap, libraries/ui/src/__snapshots__/HeroSection.test.tsx.snap, libraries/ui/src/default-config/tailwind.css
This is used in some shared components e.g. CTALinkOrButton, but only defined in website, so the styles don't get applied properly in the other apps.
Also .text-on-dark is not necessary - people should just use the normal .text-color-text-on-dark.
Part of #749
=> ui,website: Fix link-on-dark class portability

apps/app-template/src/pages/authed.tsx, apps/frontend-example/src/pages/authed.tsx
expiresAt is measured in ms since #704, forgot to update this
Have also checked for other usages, these two are it
=> app-template,frontend-example: Fix token expiry date view

apps/infra/src/k8s/serviceDefinitions.ts
Keycloak occasionally OOMs during periods of high load. We have plenty of memory headroom after #692, so we should give Keycloak more memory.
=> infra: Increase memory available to Keycloak

libraries/ui/src/Login.tsx, libraries/ui/src/utils/auth.tsx
Temporary fix for #761
Trade-off: This will cause users to be logged out more frequently than we intend. This is because without the offline_access scope, if the user is away from the page when the access token expires they are logged out.
Related:
- https://github.com/keycloak/keycloak/issues/20517
=> auth: Temporary fix for refresh tokens missing audience claim

apps/website/src/components/Nav.tsx, apps/website/src/components/lander/getCtaUrl.ts, apps/website/src/pages/404.tsx, apps/website/src/pages/_app.tsx, apps/website/src/pages/about.tsx, apps/website/src/pages/certification.tsx, apps/website/src/pages/contact.tsx, apps/website/src/pages/courses/[courseSlug]/index.tsx, apps/website/src/pages/join-us.tsx, apps/website/src/pages/join-us/ai-safety-teaching-fellow.tsx, apps/website/src/pages/join-us/swe-contractor.tsx, apps/website/src/pages/privacy-policy.tsx, apps/website/src/pages/profile.tsx, libraries/ui/src/Login.tsx
Enables SSR on the website
Almost everything seemed to work out of the box, except for:
- Dynamic page titles. This is because some of the page titles had nested components, which not actually allowed in Next.js, but we just didn't catch it because we had disabled SSR: https://github.com/vercel/next.js/discussions/38256. I've fixed this by ensuring any dynamic titles are just single strings.
- Getting and setting the query params from the URL in the login flow. This is because `window` is not defined on the server, so it throws an error when rendering. I've now gated the calls in a check for window or in a useEffect hook (which only runs client-side).
Fixes #747
- Checked the static pages (e.g. home, about us, join us)
- Checked the course listing, unit listing, FOAI lander, FOAI unit …
=> website: Enable SSR

apps/website/src/pages/api/courses/exercises/[exerciseId]/index.ts, apps/website/src/pages/api/courses/exercises/[exerciseId]/response.ts, libraries/ui/src/ErrorView.tsx
Either, the exercise should be:
- marked as optional everywhere, including in the `GetExercise` type; or
- marked as mandatory everywhere, including in the Zod types (which then requires fixing the API function)
Here it makes more sense to do the latter, and throw a 404 if someone tries to request an exercise that doesn't exist.
This was breaking unit 3 from rendering at all, because someone added an Exercise that didn't exist. With this change, just the exercise shows an error message.
Fixes #791
=> website: Fix exercise API returning invalid response rather than error when exercise does not exist

apps/website/src/components/courses/exercises/MultipleChoice.tsx, apps/website/src/lib/utils.ts
I'm not actually convinced of the utility of this. Apart from the one here, the [other case we have](https://github.com/bluedotimpact/bluedot/pull/647#discussion_r2044317855) of a string that needs to be split coming from Airtable is too different to combine in the function, and it remains to be seen if the cases will tend to be that similar (e.g. if it makes sense to trim the strings always or not).
Fixes #648
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
```
Tasks:    13 successful, 13 total
Cached:    11 cached, 13 total
Time:    12.222s
```
=> Add util for splitting comma separated strings

apps/infra/src/k8s/postgres.ts, apps/infra/src/k8s/serviceDefinitions.ts
Undeploys login-old, and moves the new login to login.bluedot.org. Also deletes the spare database we created that we're no longer using.
Fixes #679
=> infra: Deploy new keycloak

apps/website/next.config.js
Follow up from #765
This just reduces the clutter in the logs when developing locally
=> website: Enable cross-origin fonts hosting

libraries/ui/src/Login.tsx, libraries/ui/src/utils/auth.test.tsx, libraries/ui/src/utils/auth.tsx
When initially authenticating, we used the `id_token` which has an `aud` claim. This works great.
When refreshing, we mistakenly used the `access_token` instead of `id_token`. This doesn't have an `aud` claim and was the source of our pain. I think we also got confused whether the scope was relevant, which now think wasn't.
Fixes #761
=> website: Fix refresh logic by using id_token instead of access_token

apps/website/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website/src/__tests__/pages/__snapshots__/join-us.test.tsx.snap, apps/website/src/components/about/__snapshots__/BeliefsSection.test.tsx.snap, apps/website/src/components/about/__snapshots__/TeamSection.test.tsx.snap, apps/website/src/components/homepage/CommunitySection/__snapshots__/CommunityValuesSection.test.tsx.snap, apps/website/src/components/homepage/CommunitySection/__snapshots__/ProjectsSubSection.test.tsx.snap, apps/website/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap, apps/website/src/components/homepage/CommunitySection/__snapshots__/ValuesSection.test.tsx.snap, apps/website/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, apps/website/src/components/join-us/__snapshots__/ValuesSection.test.tsx.snap, libraries/ui/src/SlideList.tsx, libraries/ui/src/__snapshots__/SlideList.test.tsx.snap
SlideList should overflow to full width on mobile
This has been bothering me
- Use negative margins to accommodate standard mobile px wells
https://github.com/user-attachments/assets/a1e0d657-716f-4b2e-88d9-9b05d4013cc3
https://github.com/user-attachments/assets/76d05b32-8ada-4e33-8c50-e9fa64b4ed5a
```
```
=> SlideList should overflow to full width on mobile

apps/website-proxy/src/nginx.template.conf
I think this got deleted accidentally in #768. This results in a weird redirect to `https://bluedot.org:8080/contact/` when trying to view this page.
=> website-proxy: Fix contact page

apps/website/src/lib/api/db/tables.ts, apps/website/src/pages/api/certificates/request.ts
This PR fixes the certificate request endpoint.
When upgrading filterByFormula expressions (#829) I think I made a mistake here - we can't filter on the actual linked record field because then Airtable tries to match the record name rather than ID. So we need to filter on a linked field that has the record id as a string. This is what we were doing previously, but I changed it to the linked record field.
This PR adds the record id string field, and filters using that. I've tested locally and it fetches the exercises correctly.
It would be nice to figure out how to clean this up a little, or at least have a convention for how to do this.
Fixes #845
=> website: Fix certificate request endpoint

apps/website/src/pages/attendance-policy.tsx, apps/website/src/pages/running-versions-of-our-courses.tsx
Content taken directly from previous CMS
These are the only other pages on bluedot.org that are not migrated to the new website. With these two, we can shut off the old bluedot.org website for good (and kill website-proxy). (We do still need Wordpress for AISF and Biosecurity Fundamentals though right now).
An alternative would be to migrate these onto the blog. We might do this later, but that would require setting up redirects etc. which I thought would take longer and be more fiddly than this.
=> website: Add attendance policy and course running guide

apps/app-template/src/pages/login/index.tsx, apps/app-template/src/pages/login/oauth-callback.tsx, apps/frontend-example/src/pages/login/index.tsx, apps/frontend-example/src/pages/login/oauth-callback.tsx, apps/room/src/pages/login/index.tsx, apps/room/src/pages/login/oauth-callback.tsx, apps/website/src/components/courses/ResourceListCourseContent.tsx, apps/website/src/components/courses/exercises/FreeTextResponse.tsx, apps/website/src/components/courses/exercises/MultipleChoice.tsx, apps/website/src/components/courses/exercises/__snapshots__/FreeTextResponse.test.tsx.snap, apps/website/src/components/courses/exercises/__snapshots__/MultipleChoice.test.tsx.snap, apps/website/src/pages/login/index.tsx, apps/website/src/pages/login/oauth-callback.tsx, libraries/ui/README.md, libraries/ui/src/Login.test.tsx, libraries/ui/src/Login.tsx
- For places where we expect users to be new users rather than returning users, it's useful to be able to direct them to the registration page directly. This is fewer clicks for them, and hopefully results in more sign ups.
- This PR adds this functionality to Login.tsx, and uses it on the website where we prompt people to sign up
https://github.com/user-attachments/assets/f7a9a794-1c00-4a71-b298-d006ee98c92c
=> login: Be able to direct new users to register

apps/website/src/pages/running-versions-of-our-courses.tsx
=> website: nit: Improve quote spacing on running-versions-of-our-courses

apps/website/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website/src/__tests__/pages/__snapshots__/join-us.test.tsx.snap, apps/website/src/components/about/__snapshots__/BeliefsSection.test.tsx.snap, apps/website/src/components/about/__snapshots__/TeamSection.test.tsx.snap, apps/website/src/components/blog/BlogListSection.tsx, apps/website/src/components/courses/exercises/__snapshots__/MultiSelect.test.tsx.snap, apps/website/src/components/homepage/CommunitySection/__snapshots__/CommunityValuesSection.test.tsx.snap, apps/website/src/components/homepage/CommunitySection/__snapshots__/ProjectsSubSection.test.tsx.snap, apps/website/src/components/homepage/CommunitySection/__snapshots__/ValuesSection.test.tsx.snap, apps/website/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap, apps/website/src/components/join-us/JobsListSection.test.tsx, apps/website/src/components/join-us/JobsListSection.tsx, apps/website/src/components/join-us/__snapshots__/JobsListSection.test.tsx.snap, apps/website/src/components/join-us/__snapshots__/ValuesSection.test.tsx.snap, libraries/ui/src/Card.stories.tsx, libraries/ui/src/Card.tsx, libraries/ui/src/__snapshots__/Card.test.tsx.snap, libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
Add isFullWidth Card option
- Add `isFullWidth` option for Cards
- Allow CTAs even if `isEntireCardClickable` by omitting URLs to the `CTALinkOrButton`
- BlogListSection and JobListSection is not rendering locally for me. Investigating access tokens.
```
```
=> Add isFullWidth Card option

apps/website/src/components/Nav/Nav.tsx, apps/website/src/components/Nav/_NavLinks.tsx, apps/website/src/components/Nav/_ProfileLinks.tsx, apps/website/src/components/Nav/__snapshots__/Nav.test.tsx.snap, apps/website/src/components/Nav/utils.ts
Fix relative parent on Nav
- No need for `relative` nav__container parent
- Underline on hover should only cover width: fit-content
- Profile drawer would overlay the Explore drawer at certain interactions. Hide content as much as possible (but avoid using `hidden` to maintain the smooth open/close transition)
```
```
=> Fix relative parent on Nav

apps/website/src/components/Nav/_NavLinks.tsx, apps/website/src/components/Nav/__snapshots__/Nav.test.tsx.snap, apps/website/src/components/Nav/utils.ts
On mobile the opacity-0 element was blocking users from clicking almost anything on the page - because it is still there, just transparent :(
This change sets the element to be hidden when closed, so it doesn't intercept any touch events.
It does mean we lose the nice animations, but the site becomes useable on mobile again - can fix this up more properly when we're back next week.
=> website: nav: hotfix overlap issues

apps/editor/src/pages/api/presigned-upload.ts
S3 SDK needs to have region specified, even though it's not used
Also set file extension so that things like `<Embed>` play nicer, as they detect file type in the URL. Maybe at some point we should just create an `<Image>` component instead (or use native markdown images).
Related to #880, #877
=> editor: Fix presigned URL generation

apps/website/src/components/projects/ProjectsListSection.tsx
Drop down to a single column on skinny screens
Before:
After:
=> website: projects: Improve mobile layout

apps/infra/src/k8s/serviceDefinitions.ts, apps/website-proxy/src/nginx.template.conf, apps/website/src/pages/_app.tsx
- Add redirects in website-proxy to:
- Handle old course URLs, e.g. `/alignment` -> `/courses/alignment`
- Migrate people from old sites with redirect hint, e.g. `https://aisafetyfundamentals.com/` -> `https://bluedot.org/?from_site=aisf`
- Add announcement banner on website shown when `from_site` is set, which tells people about the migration (see screenshot below)
- New blog added in CMS: https://bluedot.org/blog/course-website-consolidation
Also see #882
Fixes #876
=> website, website-proxy, infra: Add redirects and landers for old websites

apps/website-proxy/src/nginx.template.conf
Update nginx configuration to redirect biosecurityfundamentals.com root path to bluedot.org/courses/pandemics while maintaining the existing redirect behavior for all other paths.
=> feat(website-proxy): Add special redirect for BSF homepage to pandemics course

apps/website/src/pages/running-versions-of-our-courses.tsx
Remove duplicate "you" from "Can you we use" to "Can we use" in the facilitator training program FAQ section.
=> Fix typo in facilitator training FAQ question

apps/pg-sync-service/src/index.ts, apps/pg-sync-service/src/lib/scan.ts, apps/pg-sync-service/src/lib/schema-sync.ts
**The Problem:**
When database schema changes occur (new columns, renamed fields, data type changes, etc.), the existing synced data in PostgreSQL may become inconsistent or incomplete relative to the new schema structure.
**Why Full Sync is Required:**
1. **New Columns**: When new columns are added to track additional Airtable fields, existing records won't have data for these new fields
2. **Data Type Changes**: Schema changes might require data transformation that only a full re-sync can handle
**The Solution:**
Automatically trigger a full sync when schema changes are detected to ensure:
- New columns are populated with current Airtable data
- All existing records are updated with the correct data e.g. for data type changes
**Example Scenario:**
If you add a new field mapping to sync …
=> pg-sync-service: Perform a full sync on schema additions

.github/SECURITY.md, apps/website/public/.well-known/security.txt
docs: Update security contact email from security@ to software@bluedot.org
As the software team changes shape, we discussed combining security@ and software@ for simplicity, since they'll almost certainly go to the same person for a while.
Fixes #1039
=> docs: Update security contact email from security@ to software@bluedot.org

apps/website-proxy/src/nginx.template.conf
website-proxy: Add legacy curriculum and course URL redirects to nginx config
Add 301 redirects for old curriculum and course detail pages to their new locations under /courses/, ensuring backward compatibility for bookmarked links and external references.
Fixes #1033
=> website-proxy: Add legacy curriculum and course URL redirects to nginx config

apps/website/src/components/courses/CourseSearchCard.tsx, apps/website/src/components/courses/__snapshots__/CourseDirectory.test.tsx.snap, apps/website/src/components/lander/FutureOfAiLander.tsx, apps/website/src/components/lander/__snapshots__/FutureOfAiLander.test.tsx.snap, libraries/ui/src/CourseCard.test.tsx, libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
We want to directly show the cadance set in the airtable on the website without previously changing it as done before.
=> fixes: cadance shown in coursecard

apps/website/src/pages/certification.tsx
The Postgres sync service doesn't really work with images - it syncs an expiring Airtable URL, which expires some time after the sync. This then breaks after a while.
Putting in a hardcoded generic certification badge as a temporary fix until we sort this. I think an easy route might be simply to upload the cert badges to storage.k8s.bluedot.org and link to them in Airtable as strings.
> Nothing is more permanent than a temporary solution.
=> website: Replace dynamic certificate badge with hardcoded URL temporarily

libraries/db/src/schema.ts
Not present on all records, and was causing errors when trying to sync
=> Make zoomAccount field nullable in groupDiscussionTable schema

apps/app-template/src/pages/api/authed/update-name.ts, apps/app-template/src/pages/api/public/people.ts, libraries/db/README.md, libraries/db/src/lib/client.ts
- Replace `airtableInsert/Update/Delete` with `insert/update/delete`
- Replace direct PostgreSQL queries with `scan` method
- Add filter operations support for querying records
- Update API routes to use new unified database methods
- Deprecate raw PostgreSQL write operations to prevent sync issues
---
Have only migrated app-template over. Should migrate all the other apps over sometime.
=> db: Refactor database client API to simplify usage and align more with airtable-ts

apps/website/src/__tests__/pages/profile.test.tsx, apps/website/src/lib/schemas/user/me.schema.ts
Current regex prevents certain valid names, this fixes that
Fixes #1057 
No visual change
=> Removed regex requirement for name

apps/infra/src/k8s/serviceDefinitions.ts
Remove the hosts array from pg-sync-service definition in serviceDefinitions.ts given this app does not have any need to be exposed publicly.
=> infra: Unexpose pg-sync-service

apps/website/src/__tests__/pages/courses/[courseSlug]/units/[unitNumber].test.tsx, apps/website/src/components/courses/ResourceListCourseContent.tsx, apps/website/src/components/courses/UnitFeedback.test.tsx, apps/website/src/components/courses/UnitFeedback.tsx, apps/website/src/components/courses/UnitLayout.test.tsx, apps/website/src/pages/api/courses/[courseSlug]/[unitNumber]/feedback.ts, apps/website/src/pages/api/courses/[courseSlug]/[unitNumber]/index.ts, apps/website/src/pages/api/courses/[courseSlug]/[unitNumber]/resources.ts, apps/website/src/pages/courses/[courseSlug]/[unitNumber].tsx
Reduce confusion about what is a unitId and unitNumber
This did require changing the feedback component and API to always use unitNumber, because otherwise Next complains with:
```
Error: You cannot use different slug names for the same dynamic path ('unitId' !== 'unitNumber').
at Array.forEach (<anonymous>)
```
(we could have avoided this by doing something like `/unit/by-number/{number}` but given it's just one route it's easier to be consistent)
Fixes #1046
No visual changes
=> website: Correct usage of terms unitId and unitNumber

apps/website/src/components/settings/SettingsLayout.tsx, apps/website/src/components/settings/__snapshots__/SettingsLayout.test.tsx.snap
Fixes #1090. The settings text in the breadcrumb is no longer hyperlinked. 
Not applicable since we're just fixing a bug.
No visual changes
=> [BUG] Prevent the non-existing "settings" page from being linked

apps/website/src/pages/blog/[slug].tsx
Fix previews for several sites, Notion specifically uses open graph alongside other social media platforms which was called out in the original bug
This should change our Notion preview to match the requested format in the bug request.
Fixes #1099 
Not applicable
No changes visually.
=> Fix blog previews

apps/website/src/components/courses/CertificateLinkCard.tsx, apps/website/src/components/lander/FutureOfAiLander.tsx, apps/website/src/pages/courses/[courseSlug]/[unitNumber].tsx, libraries/ui/src/Login.tsx
This PR pushes events from our user journey defined [here](https://docs.google.com/document/d/1Sm89Bv-QjPDKpSNLZn8yRn1XdbhYbsqTX-XIqugfV1k/edit?tab=t.0) onto the Google Tag Manager data layer. We will then configure tag manager to send these to Google Ads for better tracking of our goals
First part of https://github.com/bluedotimpact/bluedot/issues/1086
=> Google Ads conversion tracking 

apps/website/src/components/courses/exercises/MultipleChoice.tsx
Weird quirk of how multiple choice exercises were implemented was causing Safari to always use the default value for MC selections.
Fixes #1078 
N/A 
N/A
=> [P1 Bug] Fix Multiple Choice exercises being broken in Safari

apps/website/src/__tests__/pages/__snapshots__/about.test.tsx.snap, apps/website/src/components/Nav/_NavLinks.tsx, apps/website/src/components/about/__snapshots__/IntroSection.test.tsx.snap
This autohides the navbar ones a selection has been made. 
Fixes https://github.com/bluedotimpact/bluedot/issues/1116
https://github.com/user-attachments/assets/ebf27db5-607d-409e-90eb-65396106632c
=> fix: autohide navbar after selection

apps/website/src/pages/join-us/[ashbyIdOrCmsSlug].tsx
Previously we were showing an error when the job posting hadn't fully loaded yet. This fixes that bug.
Fixes https://github.com/bluedotimpact/bluedot/issues/1106
https://github.com/user-attachments/assets/89dab041-2e3a-44a8-85f0-c1de3344e8ed
=> fix: error page when opening job description

apps/website/src/components/Nav/_NavCta.tsx, apps/website/src/components/Nav/__snapshots__/Nav.test.tsx.snap
For very small phones below 370px there isn't enough space on the navbar for the CTA which resulted in no padding and ackward design. This is hiding the CTA in the navbar for these phones. 
Note that this affects a very small number of phones (iPhone 5 below, Samsung Galaxy s8 etc.)
Fixes https://github.com/bluedotimpact/bluedot/issues/986
https://github.com/user-attachments/assets/f7bbb500-81d6-449e-99e3-6d2c300855f2
=> fix: hide signup on very small screens

apps/website/src/components/Nav/_NavCta.tsx, apps/website/src/components/Nav/__snapshots__/Nav.test.tsx.snap
Fixed the on-scroll outline for secondary button on dark in nav (desktop)
Fixes #591
=> [fix]: secondary button on dark in nav

libraries/ui/src/Select.stories.tsx, libraries/ui/src/Select.test.tsx, libraries/ui/src/Select.tsx, libraries/ui/src/__snapshots__/Select.test.tsx.snap, libraries/ui/src/index.ts
The new designs for course settings require a select button (button that offers a drop down menu when clicked). Since we didn't already have a library component for it, I've made in this PR.
I've also added Storybook stories for this. 
Can be used everywhere on the site but was immeidately needed for #571 and #572 
Implemented select in storybook (note that we don't have identical icon libraries installed already, which is why they look slightly different)
Original designs from Figma for the cohort change select
=> [Feature] Add select to UI library for course settings

apps/website/src/pages/api/users/me.ts, apps/website/src/pages/login/oauth-callback.tsx
This fires a new google tag that includes whether the user is a new customer. we will use this to optimize for new users only.
```
{
event: "CompletedSignup",
gtm: {uniqueEventId: 28, start: 1753360059289},
new_customer: true
}
```
Fixes https://github.com/bluedotimpact/bluedot/issues/1105
=> feat: only count new customer sign ups

libraries/db/src/schema.ts
Inserts into course registration is failing because hasDroppedOut hasn't been added in all of the API requests that deal with the table. I've also made the default False.
=> [bug] Remove notNull requirement for hasDroppedOut

apps/pg-sync-service/src/index.ts, apps/pg-sync-service/src/lib/cron.ts, apps/pg-sync-service/src/lib/pg-sync.ts
Following a recent sync issue that prevented users from seeing their certificates (which was resolved through manual syncing), this PR improves the sync code to prevent future resync failures. Changes are minimal and focused on addressing specific issues in the existing implementation.
- **Fixed race condition**: Webhooks were causing resync attempts to be skipped and then marked as completed
- **Improved sync completion logic**: Sync is now marked complete only after all data is inserted into PostgreSQL (previously marked complete after loading into memory from Airtable)
- **Modified when incremental sync last occured timestamp**: Only marks incremental sync as updated when actual changes occur within the timeframe
Confirmed sync functionality works correctly with local PostgreSQL …
=> [Feature] Improve DB sync reliability

apps/website/src/components/courses/Embed.tsx, apps/website/src/components/courses/SideBar.tsx, apps/website/src/components/courses/UnitLayout.tsx, apps/website/src/components/courses/__snapshots__/SideBar.test.tsx.snap, apps/website/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap, libraries/db/src/schema.ts
Implements the new sidebar + link breadcrumb design.
**Out of scope (separate features):**
- **Progress tracking**: In this PR, time/chunk estimates and completion hidden when unavailable
- **Content type icons**: In this PR, all items use the same icon until text/exercise/reflection fields are added to the chunk table in the database
- **Exercise type headers**: In this PR, headers display only chunk names until introduction/exercise/reflection is added as a field to the chunk table in the database
Fixes #1149
=> [feat]: new sidebar

apps/infra/src/k8s/ingress.ts
- Disable strict path validation in ingress-nginx configuration
- Resolves compatibility issues with cert-manager ACME HTTP01 challenges
- References upstream issues and documentation for context
- https://cert-manager.io/docs/releases/release-notes/release-notes-1.18/#acme-http01-challenge-paths-now-use-pathtype-exact-in-ingress-routes
- https://github.com/kubernetes/ingress-nginx/issues/11176
=> Fix ingress-nginx path validation for cert-manager compatibility

apps/website/src/components/courses/ResourceListCourseContent.tsx, apps/website/src/globals.css, apps/website/src/pages/api/courses/resource-completion/[unitResourceId]/index.ts
The icon to the left of the title has been excluded from the new designs for now. Since implementing site specific icons was out of scope for v1, keeping it felt redundant - especially because we already have an icon to the right of the header that indicates when a link opens in a new tab. We'll revisit this after we develop a way to display different icons based on the resource type.
Completes most of #1147. 
https://github.com/user-attachments/assets/cebb3108-0655-4b5e-beb5-c5e20758f1d0
=> [Feature] Resource Cards Redesign

apps/infra/src/k8s/observability.ts
`infra` deployments have been failing recently, with this as the apparent main error ([example](https://github.com/bluedotimpact/bluedot/actions/runs/16909987805/job/47909624064)):
```
Diagnostics:
kubernetes:helm.sh/v3:Release (loki):
error: 1 error occurred:
* Helm release "monitoring/loki" failed to initialize completely. Use Helm CLI to investigate: failed to become available within allocated timeout. Error: Helm Release monitoring/loki: context deadline exceeded
```
There is at least one example of the deployment passing since this issue started: [example](https://github.com/bluedotimpact/bluedot/actions/runs/16918610369/job/47939344927).
I haven't spent that long looking into this, so I don't have a very good understanding of how the whole system works, but I think it's quite likely …
=> [Bug] Increase timeout of loki deployment, attempting to fix flaky app/infra deployments

apps/website/src/components/courses/exercises/FreeTextResponse.tsx, apps/website/src/components/courses/exercises/__snapshots__/FreeTextResponse.test.tsx.snap
Buttons for exercises (when not logged in) are now responsive on mobile.
Fixes #1166
=> [fix]: responsive mobile buttons

apps/posthog-proxy/src/nginx.template.conf
A bug introduced by #1186 is that localhost was no longer an origin allowed by posthog-proxy, which resulted in this error when running the website (and a CORS error in the console):
#1175
1. Docker must be running
2. Run posthog-proxy locally:
```bash
git checkout master
cd apps/posthog-proxy
npm run start
```
3. Ping it with a curl request:
```
curl -i -X POST -H "Origin: http://localhost:8000" -H "Content-Type: application/json" -d '{"test": "data"}' http://localhost:8000/e/
```
On this branch the result should have `Access-Control-Allow-Origin: https://localhost:8000` in the response, whereas on master it won't
=> [Bug] Allow localhost origin in posthog-proxy

libraries/db/src/schema.ts
**TL;DR:** Webhook syncing broke when a field was removed from an Airtable base/table. The webhook appeared healthy but was actually in an "INVALID_HOOK" state and stopped receiving updates. I attempted to make webhooks more resilient by: 1) detecting INVALID_HOOK payloads and recreating webhooks without broken fields, and 2) identifying incorrect fields when starting pg-sync-service. However, I'm still blocked by #1190 since the data shape from Airtable differs from our schema, causing unrecoverable errors. So for now, I just deleted & updated the field so that the existing pg-sync-code would work again.
---
Syncing broke for a base/table because an existing webhook expected a field to exist that had been removed. This caused our code to incorrectly think the webhook was healthy and …
=> [bug] Webhooks broken because specific field didn't exist anymore

apps/pg-sync-service/src/lib/pg-sync.ts, apps/pg-sync-service/src/lib/webhook.ts
Related to #1196 and #1203. 
These were the changes that enabled me to fix the previous unhealthy webhook states locally. I wasn't planning on pushing these changes but they should at least unblock prod since my locally synced pg-sync-service has the correct unit resources but prod does not (even after doing a full sync in prod)
[The issue that I've described at the bottom of this issue has not been resolved and is still an ongoing problem if we delete another field that is being used. ](https://github.com/bluedotimpact/bluedot/issues/1196#issuecomment-3194600516)
Related to #1196 and #1203. 
Fixes #
Not applicable
None
=> [feature] Handle INVALID_HOOK error during payloads, and recreate unhealthy web hooks during intialization

apps/infra/src/k8s/observability.ts
Loki is currently failing to deploy due to a timeout error, I previously tried [raising the timeout](https://github.com/bluedotimpact/bluedot/pull/1187) but it still fails.
After investigating in Kubernetes, it seems that it's failing to deploy due to anti-affinity rules:
```
> kubectl get events -n monitoring --sort-by=.metadata.creationTimestamp | tail -10
LAST SEEN   TYPE      REASON              OBJECT                              MESSAGE
40m         Warning   FailedScheduling    pod/loki-gateway-b6855b66d-27jtq    0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```
(This is after killing the Pending pod once, before that it had been pending for 20h):
```
wh@whcea infra % …
```
=> Override loki anti-affinity rules to allow it to deploy

apps/website/src/components/courses/FaviconImage.tsx, apps/website/src/components/courses/ResourceListCourseContent.tsx
Implemented favicons from resource websites for all resource cards. "As a user I want to see the thumbnails of the websites hosting a resource, so that I can quickly get a better feeling for where I am landing."
Note that this new component requests favicons at render time, so there's no need for extraction of full-page thumbnails, SVGs or storage.
Fixes #1157
=> [feat]: resource favicons

apps/infra/src/k8s/certManager.ts, apps/infra/src/k8s/ingress.ts, apps/infra/src/k8s/observability.ts, apps/infra/src/k8s/postgres.ts
Pin all Helm chart versions in infra to latest available versions to prevent automatic updates that can cause breakages.
Without pinned versions, Helm charts automatically pull the latest version during deployments, which can introduce breaking changes that require manual fixes (see #1202 and #1165 for examples).
- ingress-nginx: 4.13.1
- cert-manager: v1.18.2  
- kube-prometheus-stack: 76.4.0
- opentelemetry-collector: 0.130.2
- loki: 6.36.1
- cloudnative-pg: 0.26.0
All versions pinned to latest available as of 2025-08-20.
=> Pin Helm chart versions in infra

libraries/db/src/schema.ts
These are all the schema changes that I believe are required for adding [Next discussion info](https://github.com/bluedotimpact/bluedot/issues/1209) and [Group switching](https://github.com/bluedotimpact/bluedot/issues/1210). I'm putting these out now so they are ready to use in development.
I'll shortly put up another PR which sets up the scaffolding for displaying group discussions, and then we should be able to work on individual features (buttons in [this Figma](https://www.figma.com/design/6PJJZThivMuDTZ9xcoWvBs/Group-switching-UI?node-id=3037-441&t=s6zDvjAAKGInxNQz-0)) in parallel.
#1209, #1210
I have tested this on a local instance of Postgres + pg-sync-service, the fields do come through and I was able to select on them in #1221
=> [Feature] Schema changes to support group discussion and group switching UI

apps/website/src/pages/api/courses/[courseSlug]/[unitNumber]/groupDiscussion.ts, libraries/db/src/schema.ts
Reverts [one commit](https://github.com/bluedotimpact/bluedot/pull/1220/commits/f8ef104af184a33676f20f08f81825b223b16ec4) from #1220 which I added to make the type of `unitNumber` consistent across tables. It turns out the type is actually different in the "Course runner" base vs "Course builder", and this is causing the syncing of `group_discussion` to fail.
By default, deploying this PR will cause an error like "Failed to update database schema: column "unitNumber" cannot be cast automatically to type numeric" when deployed. I'll manually drop and re-add the column in the db just before deploying to work around this (I could do two deployments to drop and re-add the column, but given the syncing is already failing I think it's best to get this out as quick as possible).
#1209
=> [Bug] Fix type of unitNumber in groupDiscussionTable

apps/website/src/components/courses/UnitLayout.tsx
#1234 introduced a bug into staging where if a chunk has content but no resources or exercises, React renders "0" text on the page.  
Auto-generated message: 
Refactor conditional rendering logic in UnitLayout component
Replace nested conditional statements with ternary operator for cleaner code structure when displaying chunk resources and exercises.
| Before | After |
| <img width="894" height="456" alt="CleanShot 2025-08-24 at 10 37 06@2x" src="https://github.com/user-attachments/assets/2140391f-5b6b-4467-ac4b-ea54842946ef" /> | <img width="862" height="418" alt="CleanShot 2025-08-24 at 10 37 03@2x" src="https://github.com/user-attachments/assets/104cfd67-456f-40b8-9882-1f64bb009842" /> |
=> [Bug]: Prevent "0" being treated as text, rather than as a truthy condition.

apps/website/src/components/courses/MobileCourseModal.tsx, apps/website/src/components/courses/SideBar.tsx, apps/website/src/components/courses/__snapshots__/SideBar.test.tsx.snap, apps/website/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
Super small fix. The circle wasn't vertically centred, which bugged me. 
Changed "start" to "center" in the code. 
Before on the left, after on the right.
=> Fix sidebar chunk alignment from start to center

apps/website/src/components/courses/CourseDirectory.stories.tsx, apps/website/src/lib/hooks/useCourses.ts, apps/website/src/pages/api/courses/index.ts, libraries/db/src/schema.ts
- Add status field to course table schema
- Update API to filter courses by 'Active' status
- Move displayOnCourseHubIndex filtering to frontend hook
This endpoint is shared by the profile page so the filter shouldn't be hardcoded here. This is blocking me from testing #1217 .
Fixes #
Can confirm it filters properly!
| 📸 |  |
| 📱  |  |
| 🖥️ |  |
=> Filter courses by status instead of displayOnCourseHubIndex in the API endpoint

apps/website/src/components/AnnouncementBanner.test.tsx, apps/website/src/components/AnnouncementBanner.tsx, apps/website/src/pages/_app.tsx, apps/website/src/stores/announcementBanner.ts
Closes #731.
1. Creates a new Zustand store for tracking which announcement banners have been dismissed. Although the original issue mentions `localStorage` we already use Zustand for cookie consent - I copied that pattern.
2. Adds a new '×' (close) button for closing a currently open announcement -> this updates the store.
3. Make `AnnouncementBanner` a pure client component by explicitly removing it from SSR using `dynamic`. This is needed because reading/writing to `localStorage` (what Zustand does under the hood) can only be done on pure client components.
4. Introduce `getAnnouncementBannerKey` which will hash the banner children to produce a unique key for the banner (used for tracking dismissal). A little more dev effort now but future authors won't need to think of a new ID for …
=> [Feature] Allow announcement banners to be dismissed

apps/website/src/components/courses/UnitLayout.test.tsx, apps/website/src/components/courses/UnitLayout.tsx, apps/website/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
- Add keyboard shortcuts 1-9 to jump directly to specific units
- Update keyboard navigation hint to include new shortcuts
- Provide accessibility announcement when navigating via number keys
I want to navigate units faster. This is the most intuitive way to do it in my mind. 
It takes the user to the first chunk of the unit number they select. E.g. if they're currently on unit 3, chunk 4, and they press the '2' key, it will take them to the first chunk in unit 2.
=> Add number key navigation for units in course layout

apps/website/src/components/courses/MarkdownExtendedRenderer.tsx
While our React resource card components correctly open links in new tabs, links rendered in markdown (used throughout our courses, including the entire FOAI course, portions of others) were opening in the same tab, causing users to navigate away from their lesson.
I updated the MarkdownExtendedRenderer to open all external links in new tabs. This prevents users from accidentally leaving their course and maintains their learning flow.
This approach aligns with industry standards (Coursera, Khan Academy, etc) to ensure external resources enhance rather than interrupt the learning experience
Fixes #1168 
N/A
=> [feat]: prevent user dropout

apps/infra/Pulumi.prod.yaml, apps/infra/src/k8s/secrets.ts, apps/infra/src/k8s/serviceDefinitions.ts, apps/pg-sync-service/src/env.ts, apps/pg-sync-service/src/lib/webhook.ts, libraries/db/src/schema.ts
We encountered a `TOO_MANY_WEBHOOKS_IN_BASE` Airtable error that was causing the production pg-sync-service to get stuck creating webhooks.
Airtable has a maximum limit of 10 webhooks per base. I've added a new environment variable to k8s: `PROD_ONLY_WEBHOOK_DELETION="TRUE"`. This is configured for prod only
This setting allows the production server to delete old webhooks when needed, so it stays in sync with Airtable. By restricting webhook deletion to production only, we prevent developers syncing locally from accidentally deleting the production webhook and breaking prod sync.
I've tested this locally and confirmed the code successfully:
- Catches the Airtable `TOO_MANY_WEBHOOKS_IN_BASE` error response
- Initiates deletion of old webhooks when the env variable is set to `TRUE`
=> [fix] Allow for prod to delete webhooks during sync

apps/website/next-env.d.ts, apps/website/src/components/courses/KeyboardNavMenu.test.tsx, apps/website/src/components/courses/KeyboardNavMenu.tsx, apps/website/src/components/courses/UnitLayout.test.tsx
- Consolidate navigation shortcuts into single "Navigate sections" entry
- Remove popover title by default for cleaner UI
- Update dialog aria-label for better accessibility
- Fix test assertions to match new menu structure
I felt the new keyboard shortcuts design was wordy, so I've simplified it. 
Users don't know what "Units" and "Chunks" are, so I don't think we should use these words publicly. Sections is more intuitive imo.
"Inside course" doesn't mean anything to me, so I deleted it too. 
| **Old** | **New** |
| --- | ---- | 
| <img width="1274" height="680" alt="CleanShot 2025-08-30 at 14 29 27@2x" src="https://github.com/user-attachments/assets/6fe61487-39f2-4296-8316-0e7cd842ac04" /> | <img width="1188" height="424" alt="CleanShot 2025-08-30 at 14 29 03@2x" …
=> [Feat] Simplifying the keyboard shortcut popup

apps/website/src/components/courses/ListenToArticleButton.test.tsx, apps/website/src/components/courses/ListenToArticleButton.tsx, apps/website/src/components/courses/ResourceListItem.test.tsx, apps/website/src/components/courses/ResourceListItem.tsx, apps/website/src/components/courses/__snapshots__/ListenToArticleButton.test.tsx.snap, apps/website/src/components/courses/__snapshots__/ResourceListItem.test.tsx.snap
Adds a "Listen to Article" feature that allows users to listen to audio versions of course resources via Spotify. The button is displayed in resource cards when available and is responsive on mobile. Added new snapshot tests accordingly.
As discussed in #1148, native media player would be separated into a future issue if it is decided that it should be prioritized.
Fixes #1148
=> [feat]: listen to article

apps/infra/src/vultr/vke.ts
From the issue #1266 :
>The version shown in the [Vultr web UI](https://my.vultr.com/kubernetes/manage/?id=83dad468-420e-4bdb-a5da-5b5395b22bdc#subsupgrade) is actually 1.32.1+1, and running `kubectl version` locally confirms this (client/server mismatch is just a local issue):
>```
>> kubectl version
>Client Version: v1.34.0
>Kustomize Version: v5.7.1
>Server Version: v1.32.1
>Warning: version difference between client (1.34) and server (1.32) exceeds the supported minor version skew of +/-1
>```
#1266
N/A
On master, running `pulumi preview --diff --show-config` should give an output that looks like this:
```
pulumi preview --diff --show-config
Previewing update (prod):
Configuration:
infra:airtablePat: [secret]
infra:alertsSlackBotToken: [secret]
infra:anthropicApiKey: [secret] …
```
=> [Bug] Upgrade vke-cluster to the version that is actually live (1.32.1+1)

libraries/db/src/schema.ts
PG has already set year as a text column, which is making drizzle use an alter table command (which ends up failing) instead of dropping the column and adding it back.
I'll follow this up with another schema change to make year numeric. I've tested this all locally and can confirm that this was the issue
Fixes #
https://github.com/bluedotimpact/bluedot/commit/5e419368c56fbe5d05df09ea582826f504c03e9b
=> Remove year so that Drizzle doesn't attempt to alter the existing year data but rather drop it and re-add it as a different type

libraries/db/src/schema.ts
Fixes how prod originally have year as a text, and couldn't directly alter the column from text to number automatically.
https://github.com/bluedotimpact/bluedot/pull/1277
Fixes 
https://github.com/bluedotimpact/bluedot/commit/5e419368c56fbe5d05df09ea582826f504c03e9b
Will only merge this after prod changes the schema to remove year.
=> [fix] Make year numeric after having it removed completely

apps/infra/src/vultr/vke.ts
I won't merge this until after [Upgrade vke-cluster to the version that is actually live (1.32.1+1)](https://github.com/bluedotimpact/bluedot/pull/1267) is deployed. There is some risk with this PR of the load balancer IP changing (this is the main entry point into the website and production database), copying [this comment](https://github.com/bluedotimpact/bluedot/issues/1266#issuecomment-3241563281) from the issue regarding that:
> An alternative would be to first update the load balancer to definitely use a static IP, and then proceed with the upgrade. The reasons I think it not worth doing it this way are:
>
>1. I think it's very unlikely that the load balancer IP will change. Reasoning:
>  a. It is an external resource created by the 'ingress-nginx' service, not a Kubernetes node …
=> [Bug] Upgrade vke-cluster to latest version (v1.33.0+3)

libraries/db/src/schema.ts
I added a field called "autoNumberId" to various tables which is an auto-incrementing and unique number for each row. "AutoNumber" is a specific type in Airtable that provides the newest rows the highest number.
Turns out that using record_id does not ensure that you actually get the most recent or a stable sort. I also couldn't use something like the created_at field because that doesn't backfill. 
Just schema changes for now, I've tested a sync locally and can confirm it's non-breaking.
Exercise and resource completions, amongst other backend APIs, have multiple rows and are code is breaking when we otherwise are expected a single value. Adding this column to allow us to consistently just return the most recent value. 
N/A
=> [fix] Schema changes to prevent duplicate rows

apps/posthog-proxy/src/nginx.template.conf
PostHog analytics dropped to zero with no obvious cause on 2025-08-25, and came back when I [upgraded Kubernetes](https://github.com/bluedotimpact/bluedot/issues/1266#issuecomment-3248563311) on 2025-09-03, which caused the pod to restart.
I looked at the [logs in Grafana at the time the problem started](https://grafana.k8s.bluedot.org/a/grafana-lokiexplore-app/explore/k8s_deployment_name/bluedot-posthog-proxy-deployment/logs?from=2025-08-25T13:00:00.000Z&to=2025-08-25T13:27:40.000Z&var-ds=fekp33muo5pfka&var-filters=k8s_deployment_name%7C%3D%7Cbluedot-posthog-proxy-deployment&patterns=%5B%5D&var-lineFormat=&var-fields=&var-levels=&var-metadata=&var-jsonFields=&var-patterns=&var-lineFilterV2=&var-lineFilters=&timezone=browser&var-all-fields=&displayedFields=%5B%5D&urlColumns=%5B%5D&visualiz …
=> [Bug] Support dynamic DNS resolution in posthog-proxy

apps/website/src/pages/_app.tsx
Fixing a trailing whitespace which was causing [this action](https://github.com/bluedotimpact/bluedot/actions/runs/17594019770) to fail.
=> Remove trailing whitespace from announcement banner text

apps/website/src/components/courses/UnitLayout.tsx, apps/website/src/pages/courses/[courseSlug]/[unitNumber]/[[...chunkNumber]].tsx
Cleaning up a quick change (#1306) made during an outage earlier. Still allow the page to load if there is an error loading the group discussion, but show a banner so users can report this.
Fixes #1309 
N/A
| 📸 |  |
| 📱  |  |
| 🖥️ | <img width="3014" height="1640" alt="Screenshot 2025-09-09 at 22 43 22" src="https://github.com/user-attachments/assets/659de9f4-edb5-4a65-929b-1f6e76f674c3" /> |
=> [Feature] Display error when group discussion fails to load

apps/pg-sync-service/src/lib/cron.ts, apps/pg-sync-service/src/lib/pg-sync.test.ts, apps/pg-sync-service/src/lib/pg-sync.ts, apps/pg-sync-service/src/lib/scan.test.ts, apps/pg-sync-service/src/lib/scan.ts, apps/pg-sync-service/src/lib/schema-sync.ts, apps/pg-sync-service/src/lib/sync-manager.ts, apps/pg-sync-service/src/lib/webhook.ts, libraries/ui/README.md, libraries/ui/src/api.ts, libraries/ui/src/utils/makeMakeApiRoute.ts, libraries/utils/src/slackNotifications.ts
Implements direct Slack calling to notify us when critical errors occur in our `pg-sync-service`.
We have two Slack channels for notifications. For the new `slackAlert` calls we rely on the env variable `ALERTS_SLACK_CHANNEL_ID`, which is used for critical error handling.
For informational messages (e.g. sync started/completed) it would be better if we send to our non-critical Slack channel. I'm not sure of the best way to handle multiple channel IDs without cluttering the env. For now I've added a Grafana alert that is linked to a new Slack contact point which will send a message to this 'informational' channel. Going forward it would be nice to include this in our `observability.ts` so that we have deterministic setup. 
Fixes #1293.
=> Slack notifications for `pg-sync-service` errors

apps/website/src/components/lander/agi-strategy/QuoteSection.tsx
The AGI strategy lander quote carousel had two UX issues:
1. **Jumpy transitions** - Clicking a tab didn't reset the auto-rotation timer, potentially causing quotes to switch immediately after user interaction (e.g., click a tab, then 1 second later it auto-advances)
2. **Interrupts reading** - Timer continued running while users hovered over quotes, potentially switching content while they were actively reading
Improved logic:
- Resets the 11-second timer whenever a user clicks a tab indicator
- Pauses auto-rotation when hovering over the quote section
- Resumes auto-rotation when mouse leaves the section
Implements #1344, leaving issue open pending potential additional design updates cc @dewierwan @herrhaase
=> [feat + fix]: quote module enhancements - timer reset and hover pause

apps/website/src/components/about/HistorySection.test.tsx, apps/website/src/components/join-us/JobsListSection.test.tsx, apps/website/src/components/join-us/ValuesSection.test.tsx, libraries/ui/src/SlideList.test.tsx
Two problems:
1. We were calling `afterAll`, not `afterEach`, so the call to `clearAllMocks` was needing to be directly invoked
2. Prefer `restoreAllMocks` to `clearAllMocks`. `isMobile` is not a function, which means it is treated as a property descriptor. From the [vitest docs](https://vitest.dev/api/vi.html#vi-restoreallmocks): `restoreAllMocks` will '...  restore original descriptors of spied-on objects.' This is not the case for `clearAllMocks`. I tested this by logging the value of `isMobile` within the component and validating that it is always reset to `false` unless you explicitly over-ride the mock.
Fixes #482 
NA
NA
=> [Fix]: `isMobile` from device detect not reset between tests

apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap, apps/website/src/components/lander/agi-strategy/CourseDetailsSection.test.tsx, apps/website/src/components/lander/agi-strategy/CourseDetailsSection.tsx, apps/website/src/components/lander/agi-strategy/__snapshots__/CourseDetailsSection.test.tsx.snap
Update application deadline from 19th Sep to 21st Sep for the AGI strategy course cohort starting 29th Sep. This change affects the course details section, related tests, and snapshots to reflect the extended deadline.
=> feat: update AGI strategy course application deadline to 21st Sep

apps/website/src/components/lander/AgiStrategyLander.tsx, apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap, apps/website/src/components/lander/agi-strategy/FAQSection.tsx
Implementing an FAQ section for the AGI strategy lander. I decided to isolate the component into a separate FAQsection within the directory instead of implementing directly in the lander. I also updated the section background color of the graduates section.
Implements part of #1334
=> [feat]: FAQ section + small ui changes

apps/website/src/components/lander/AgiStrategyLander.tsx, apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap, apps/website/src/components/lander/agi-strategy/WhoIsThisForSection.test.tsx, apps/website/src/components/lander/agi-strategy/WhoIsThisForSection.tsx, apps/website/src/components/lander/agi-strategy/WhyTakeThisCourseSection.tsx, apps/website/src/components/lander/agi-strategy/__snapshots__/WhoIsThisForSection.test.tsx.snap, apps/website/src/components/lander/agi-strategy/__snapshots__/WhyTakeThisCourseSection.test.tsx.snap
Adding "Who is this course for" section for the AGI Strategy lander. 
I updated icons based on new copy - @herrhaase / @dewierwan feel free to let me know if you'd prefer other icons instead.
Implements part of #1334
=> [feat]: who is this course for section

apps/website/src/components/lander/AgiStrategyLander.tsx, apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap, apps/website/src/components/lander/agi-strategy/CourseCurriculumSection.tsx, apps/website/src/components/lander/agi-strategy/CourseDetailsSection.tsx, apps/website/src/components/lander/agi-strategy/FAQSection.tsx, apps/website/src/components/lander/agi-strategy/WhoIsThisForSection.test.tsx, apps/website/src/components/lander/agi-strategy/WhoIsThisForSection.tsx, apps/website/src/components/lander/agi-strategy/WhyTakeThisCourseSection.tsx, apps/website/src/components/lander/agi-strategy/__snapshots__/CourseDetailsSection.test.tsx.snap, apps/website/src/components/lander/agi-strategy/__snapshots__/WhoIsThisForSection.test.tsx.snap, apps/website/src/components/lander/agi-strategy/__snapshots__/WhyTakeThisCourseSection.test.tsx.snap, apps/website/src/globals.css
Adding new Course Curriculum Section component with expandable/collapsible unit cards displayed in an accordion-style, fetching from Airtable db.  Responsive for desktop and mobile. 
Standardized upper padding pattern across sections for larger screen sizes (course details, faq, graduates section). Reduced upper padding for course benefits section to-spec now that the course curriculum section has been added.
**Out of scope for this PR:**
- Displaying progress-related features (blocked, will create new PR)
**Note:** I still want to test the custom scrollbar in mobile staging.
Implements part of #1334
=> [feat + fix]: course curriculum section + various larger-screen-sizes cleanup

apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap, apps/website/src/components/lander/agi-strategy/CourseCurriculumSection.tsx, apps/website/src/components/lander/agi-strategy/FAQSection.tsx
Updating from rounded chevron, open and close icons
Related to #1334, #1364, #1355
=> [fix]: update from rounded dropdown icons

apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap, apps/website/src/components/lander/agi-strategy/WhoIsThisForSection.test.tsx, apps/website/src/components/lander/agi-strategy/WhoIsThisForSection.tsx, apps/website/src/components/lander/agi-strategy/__snapshots__/WhoIsThisForSection.test.tsx.snap
Change "Who is this course for" to "Who this course is for" to improve readability and natural language flow in the WhoIsThisForSection component and update corresponding tests and snapshots.
=> fix: improve grammar in course section heading

libraries/db/src/schema.ts
Currently in GroupSwitchModal, when "permanent switch" is selected, we display the _next_ discussion time as the indicative time. This isn't ideal as a specific discussion may have moved relative to the usual recurring time. This adds the field that is the source of truth for the recurring time, to be used in a later PR
#1210
N/A
N/A
=> [Feature] Schema changes for displaying recurring group meeting time, rather than next discussion time

apps/website/src/components/courses/UnitLayout.tsx, apps/website/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
Fixes #1385. Adds truncation to overflowing text. Remove unneeded `inline-flex` and `items-center` classes from anchor elements.
| 📸 | Before | After |
|---------|---|---|
| | ![before](https://github.com/user-attachments/assets/7420a7e0-b716-454d-bad1-c7379c1f891c) | ![after](https://github.com/user-attachments/assets/fd4f4078-901c-4729-a3db-ff170bdd33d8) |
=> [Fix] breadcrumb overflow

apps/availability/src/components/TimeAvailabilityInput.tsx
Explicit handling of [touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) is only needed when you need to handle complex multi-touch interactions. Since we don't do this, I simplified our event handling by relying on more modern [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) instead of separate mouse and touch events. This makes the availability form respond to touch drags correctly.
Tested on desktop and mobile variants.
Fixes #1351.
| 📸 | Before | After |
|---------|---|---|
|  | ![before](https://github.com/user-attachments/assets/817adac1-8d34-43ea-866b-98b82b7894b8) | ![after](https://github.com/user-attachments/assets/bb0ea914-0e71-4c8a-b6cd-2880d669945a) |
=> Prefer pointer events to separate mouse and touch events

apps/website/src/components/lander/agi-strategy/CommunityMembersSubSection.tsx
Since the AGI strategy lander community subsection carousel no longer has a definitive beginning/end, the active-state and hover-state styling was updated for its arrows to reflect that. Also added cursor pointers for the clickable elements.
=> [feat]: updated carousel arrow styling

.github/workflows/website_deploy_production.yaml
Should fix this failing build: https://github.com/bluedotimpact/bluedot/actions/runs/18001215785/job/51211499261.
This change was [added to CI/CD](https://github.com/bluedotimpact/bluedot/pull/1331/commits/a65c822daae5d163b3aae172c122ab5332d23806) workflow as part of https://github.com/bluedotimpact/bluedot/pull/1331 but I didn't update the deployment pipeline.
We could instead append to `.env.production.local` since that takes precedence but I stuck with `sed` for consistency with the ci/cd workflow file.
NA
NA
=> AIRTABLE_PERSONAL_ACCESS_TOKEN secret for production build

apps/website/src/components/courses/GroupDiscussionBanner.tsx, apps/website/src/components/courses/GroupSwitchModal.stories.tsx, apps/website/src/components/courses/GroupSwitchModal.tsx, apps/website/src/lib/utils.test.ts, apps/website/src/lib/utils.ts, apps/website/src/pages/api/courses/[courseSlug]/group-switching/available.test.ts, apps/website/src/pages/api/courses/[courseSlug]/group-switching/available.ts, apps/website/src/pages/api/courses/[courseSlug]/group-switching/index.ts
The last few bits of cleanup to match the designs in the original group switching issue (#1210):
- Add info about the group being switched into to the "Success!" screen
- Add "Update availability" to the manual switching screen
- When switching permanently, use the recurring time on the group rather than the time of the next discussion. Also display this as e.g. "Wed 11:00 AM", rather than "Nov 13 11:00 AM"
- Add icons to the title of "Success!" and "We are working on your request" screens
- Don't allow switching into discussions that have already passed
- I also added some tests for the calculateGroupAvailability function used on the backend
Fixes #1210
| 📸 |  |
| 📱  | <img width="417" height="924" alt="Screenshot 2025-09-23 at 09 03 36" …
=> [Feature] GroupSwitchModal miscellaneous cleanup

apps/website/src/components/courses/GroupDiscussionBanner.tsx, apps/website/src/components/courses/UnitLayout.tsx, apps/website/src/pages/api/courses/[courseSlug]/[unitNumber]/groupDiscussion.ts, apps/website/src/pages/courses/[courseSlug]/[unitNumber]/[[...chunkNumber]].tsx
- Make GroupDiscussionBanner display for facilitators
- Show the host key in the button for facilitators, copy it to the clipboard on click
No issue, requested by @anglilian in Slack
| 📸 |  |
| 📱  | <img width="660" height="1466" alt="Screenshot 2025-09-25 at 11 42 50" src="https://github.com/user-attachments/assets/59c55b4c-7983-48e1-b8d5-baf31ffa8f59" /> |
| 🖥️ | <img width="1674" height="452" alt="Screenshot 2025-09-25 at 11 42 44" src="https://github.com/user-attachments/assets/f2bb1260-53e3-4e73-89c6-fa63bae6c0c7" /> |
=> [Feature] Show GroupDiscussionBanner for facilitators

apps/website/src/components/Nav/Nav.tsx, apps/website/src/components/Nav/_MobileNavLinks.tsx, apps/website/src/components/Nav/_NavCta.tsx, apps/website/src/components/Nav/__snapshots__/Nav.test.tsx.snap, apps/website/src/components/courses/GroupSwitchModal.stories.tsx, apps/website/src/components/courses/exercises/__snapshots__/FreeTextResponse.test.tsx.snap, apps/website/src/components/courses/exercises/__snapshots__/MultipleChoice.test.tsx.snap, apps/website/src/components/settings/__snapshots__/CourseListRow.test.tsx.snap, libraries/ui/src/utils/addQueryParam.test.ts, libraries/ui/src/utils/addQueryParam.ts
Fixes critical issue where login/signup buttons were inaccessible on small mobile devices (<370px width), preventing users from creating accounts or logging in and likely causing user drop off. Added login/signup CTA buttons to the mobile navigation drawer for smaller screens, where buttons appear in either the navbar **or** mobile drawer (never both). Chose to stack buttons in mobile to accommodate for more screen sizes.
At the same time, fixed another navbar dropdown alignment bug that occurred when resizing between mobile/desktop viewports!
Fixes #1396
=> [fix]: login + sign up appear in mobile

apps/website/src/components/lander/FutureOfAiLander.tsx, apps/website/src/pages/api/certificates/[certificateId].ts, apps/website/src/pages/api/cms/blogs/[slug]/index.ts, apps/website/src/pages/api/cms/jobs/[slug]/index.ts, apps/website/src/pages/api/cms/jobs/index.ts, apps/website/src/pages/api/cms/projects/[slug]/index.ts, apps/website/src/pages/api/courses/[courseSlug]/index.ts, apps/website/src/pages/blog/[slug].tsx, apps/website/src/pages/certification.tsx, apps/website/src/pages/courses/[courseSlug]/index.tsx, apps/website/src/pages/join-us/[slug].tsx, apps/website/src/pages/projects/[slug].tsx
Part of an overarching [ticket](https://github.com/bluedotimpact/bluedot/issues/1365) to render all content that may be needed for SEO or link previews server side. This covers all the straightforward cases.
Remaining things to do after this PR:
- There is one remaining case, `apps/website/src/pages/courses/[courseSlug]/[unitNumber]/[[...chunkNumber]].tsx`, which is a bit more complicated because `<Head>` is buried inside `<UnitLayout>`.
- I want to add tests that the head tags are set correctly. `next/head` doesn't work out of the box in tests, so I will need to use something like [this workaround](https://github.com/vercel/next.js/discussions/11060#discussioncomment-33628) I found in a discussion thread. This could be fiddly to set up so I'd like to have it reviewed separately.
#1365 …
=> [Bug] Render SEO related content server side: course lander, blog posts, job openings, projects, certificates

apps/website/src/components/lander/AgiStrategyLander.tsx, apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap, apps/website/src/components/lander/agi-strategy/HeroSection.tsx, apps/website/src/components/lander/agi-strategy/__snapshots__/HeroSection.test.tsx.snap
New requirements were added to the [figma designs](https://www.figma.com/design/62YlFNK7QS6z7SkrPjrwVb/Blue-Dot?node-id=1275-11437&p=f&t=59pOx5HeM7SyG9w2-0) for the AGI Strategy Lander hero section, so this PR implements them! 
**Specifically:**
- Adds a soft-light noise layer on the hero image
- Reverse order of stacked hero image/text on screen sizes <1024px (hero text is displayed on top of the hero image vs the reverse)
- Updated styling at 320px
Implements part of #1404
| Mobile  | Desktop |
| ------------- | ------------- |
| <img width="320" height="759" alt="mobile" src="https://github.com/user-attachments/assets/9895f13f-3f9f-458a-8691-c79eb2e76e09" /> | <img width="1512" height="760" alt="desktop" src="https://github.com/user-attachments/assets/eaa177a2-6315-4119-aa55-1a8f82794af …
=> [feat]: agi strategy hero updates

README.md
I think ideally this would be public and clearly visible to anyone who wants to contribute. Currently the project is actually private because I don't have the permissions to make it public.
=> Add kanban link to readme

apps/website/src/__tests__/testUtils.ts, apps/website/src/components/settings/CourseDetails.stories.tsx, apps/website/src/components/settings/CourseDetails.tsx, apps/website/src/components/settings/CourseListRow.tsx
Was taking a look at the `CourseDetails` component as part of #1405. Made some changes:
1. Re-use existing DB types
2. Prefer axios `loading` instead of dedicated loading state
3. Re-use existing time formatting utils
4. Prefer `last:` tailwind CSS class to prop drilling `isLast`. We can also make this change for parent components, but I didn't want this PR to get too large
5. Mock HTTP requests for stories (so that they actually work, which they didn't before?!)
As a result of re-using some of the time formatting utils the abbreviations for time units have been expanded:
| Before | After |
|---|---|
| <img width="406" height="214" alt="image" src="https://github.com/user-attachments/assets/645cf592-ab3e-409e-b266-c186daa8c7bc" /> | <img width="387" height="231" alt="image" …
=> `CourseDetails` cleanup

apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap, apps/website/src/components/lander/agi-strategy/QuoteSection.tsx, libraries/ui/src/hooks/useBreakpoint.ts
Variety of quote module enhancements:
- Larger hit-boxes, selector lines
- Navigation arrows
- Next-card stacked horizontally "peeks" to the right with full-bleed, clicking advances to next card
- Additional breakpoint support at 320px and 680px
- Updated styling from new requirements (left-aligned image, bottom-aligned names/titles)
- Text-size logic based on length of quotes
**Out of scope (PR getting too long, can be separate issue):**
- Swipe/carousel animations
Closes #1344
Also implements parts of:
- #1404 (bottom-alignment of names/titles)
- #1414 (addtl breakpoint support)
**Note:** timer reset and hover pause were already fixed in #1346
=> [feat]: quote module enhancements
