- README.md
Relevant to https://github.com/bluedotimpact/bluedot/issues/7
> docs: Updates Developer setup instructions to be one click copyable

- README.md
Converts some websites/tools to links in readme for ease of use
> feat: Adds links for ease of use to readme

- apps/meet/src/lib/api/db.ts
- apps/meet/src/pages/api/public/meeting-jwt.ts
- apps/meet/src/pages/api/public/meeting-participants.ts
> meet: Handle 0 or >1 facilitators

- apps/availability/.env.local.template
- apps/availability/src/pages/api/public/get-form.ts
- apps/availability/src/pages/api/public/submit.ts
> Update to avoid using filterByFormula

- apps/infra/package.json
- package-lock.json
See https://github.com/dirien/pulumi-vultr/issues/423
> deps: Rollback @ediri/vultr to 2.20.1

- apps/infra/src/k8s/serviceDefinitions.ts
Relies on https://github.com/bluedotimpact/bluedot/pull/32
> Add new website-25 project config for CI/CD

- .github/pull_request_template.md
- apps/website-25/src/pages/home.tsx
- libraries/ui/src/Nav.tsx
Fix lint to resolve breaking CI/CD and add new PR template
Fixes #31 
- Ran `npm run lint`
- Added new `.github/pull_request_template.md` file
```
RUN  v1.6.0 /Users/tarin-bluedot/bluedot/apps/website-25
✓ src/pages/api/status.test.ts (1)
✓ src/components/ErrorPage.test.tsx (2)
Test Files  2 passed (2)
Tests  3 passed (3)
Start at  14:33:01
Duration  620ms (transform 48ms, setup 0ms, collect 343ms, tests 10ms, environment 159ms, prepare 75ms)
```
> Fix lint take 2

- apps/infra/src/k8s/serviceDefinitions.ts
Missed an update
Fixes #31 
Missed a one line change in K8 set-up. See failure: https://github.com/bluedotimpact/bluedot/actions/runs/12831246165/job/35781392859#step:6:1
N/A
```
$ npm run test && npm run lint
```
> Missed K8 update

- .github/workflows/ci_cd.yaml
- apps/infra/README.md
Update ci_cd.yaml to include new website
Fixes #31 
This will _actually_ fix #31 
n/a
```
$ npm run test && npm run lint
```
> Update ci_cd.yaml to include new website

- .github/workflows/ci_cd.yaml
- apps/infra/README.md
Reverts bluedotimpact/bluedot#37 as the actions were [failing](https://github.com/bluedotimpact/bluedot/actions/runs/12833518396)
> Revert "Update ci_cd.yaml to include new website"

- apps/website-25/src/pages/_app.tsx
- apps/website-25/src/pages/about.tsx
- apps/website-25/src/pages/careers.tsx
- libraries/ui/src/Nav.test.tsx
- libraries/ui/src/Nav.tsx
- libraries/ui/src/__snapshots__/Nav.test.tsx.snap
Add About and Careers pages
- Add About and Careers pages
- Update Nav accordingly
- Add missing Nav testing
| 📸 |  |
| 🖥️ | <img width="1512" alt="Screenshot 2025-01-20 at 15 56 00" src="https://github.com/user-attachments/assets/a0470cb6-1916-4d86-9f11-4e5803dbadc8" /> <img width="1512" alt="Screenshot 2025-01-20 at 15 55 57" src="https://github.com/user-attachments/assets/280f51ac-f36e-47d9-b06c-7080af3248c4" /> <img width="1481" alt="Screenshot 2025-01-20 at 15 55 53" src="https://github.com/user-attachments/assets/30e4c86a-ed89-4272-b3e7-317fb0892ff6" /> |
| 📱  |  |
```
$ npm run test
Time:    1.133s 
```
```
$ npm run lint
Tasks:    9 successful, 9 total
Cached:    7 cached, 9 total
Time:    2.197s 
```
> Add About and Careers pages

- libraries/ui/package.json
- libraries/ui/src/Nav.tsx
- libraries/ui/src/__snapshots__/Nav.test.tsx.snap
- package.json
Add test:update command
- Add test:update command
- Update Nav BEM classes as an example
```
$ npm run test
✓ src/HeroSection.test.tsx (3)
✓ src/Footer.test.tsx (2)
✓ src/Nav.test.tsx (3)
Test Files  3 passed (3)
Tests  8 passed (8)
Start at  17:03:36
Duration  373ms (transform 46ms, setup 0ms, collect 339ms, tests 27ms, environment 186ms, prepare 101ms)
```
> Add test:update command

- apps/website-25/src/pages/index.tsx
- libraries/ui/src/Section.test.tsx
- libraries/ui/src/Section.tsx
- libraries/ui/src/__snapshots__/Section.test.tsx.snap
- libraries/ui/src/index.ts
Create Section component
Fixes #28 
Create section component with title (required) and optional subtitle args
| 📸 |  |
| 🖥️ | <img width="1568" alt="image" src="https://github.com/user-attachments/assets/82c5194a-664c-4647-8bcf-41a3c2ce17a1" /> |
| 📱  |  |
```
$ npm run test
Time:    1.031s 
```
> Create Section component

- apps/website-25/src/components/about/HistorySection.test.tsx
- apps/website-25/src/components/about/HistorySection.tsx
- apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap
- apps/website-25/src/pages/about.tsx
Add about/HistorySection
- Add HistorySection with internal HistoryEvent component for styling the MVP popups
| 📸 |  |
| 🖥️ | <img width="1349" alt="image" src="https://github.com/user-attachments/assets/6f5ad060-a089-4012-b77b-1a637b4e173c" /> |
| 📱  |  |
```
Time:    1.252s 
```
> Add about/HistorySection

- apps/website-25/src/pages/index.tsx
Fixes # (issue)
| 📸 |  |
| 🖥️ |  |
| 📱  |  |
```
```
> Update logo URL path

- apps/website-25/src/components/about/IntroSection.tsx
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/components/careers/CareersSection.test.tsx
- apps/website-25/src/components/careers/CareersSection.tsx
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
- apps/website-25/src/pages/about.tsx
- apps/website-25/src/pages/careers.tsx
Basic elements on the Careers page
| 📸 |  |
| 🖥️ | <img width="1483" alt="Screenshot 2025-01-22 at 16 52 48" src="https://github.com/user-attachments/assets/5e6429c4-13e1-4585-b831-314eb2ee2600" /> <img width="1502" alt="Screenshot 2025-01-22 at 16 52 38" src="https://github.com/user-attachments/assets/9139f81e-7c67-43c6-99a4-1abece9e0d28" /> |
| 📱  |  |
```
Time:    1.017s
```
> Basic elements on the Careers page

- .github/workflows/ci_cd.yaml
- apps/website-25/next-env.d.ts
- libraries/ui/tsconfig.json
- package-lock.json
Update `npm` packages that do not require attention via npm audit, add --jsx to tsconfig.json and add auto updated next-env file
N/A
See above 
N/A
N/A
```
$ npm run test
Time:    4.315s 
```
> Update package.json, tsconfig.json, and github actions to run ci/cd on pull request

- apps/website-25/src/pages/index.tsx
- libraries/ui/src/Banner.tsx
- libraries/ui/src/Footer.tsx
- libraries/ui/src/__snapshots__/Banner.test.tsx.snap
- libraries/ui/src/__snapshots__/Footer.test.tsx.snap
Move Banner into Footer as this appears to be used across pages
- Quick change to include Banner on all pages
- Added an alert on submit so that non-techies don't ask us if it is broken 😂 
| 📸 |  |
| 🖥️ | <img width="1511" alt="image" src="https://github.com/user-attachments/assets/78b2c7e7-9571-448a-9ddb-ded773f93c72" /> |
| 📱  |  |
```
Time:    857ms 
```
> Move Banner into Footer as this appears to be used across pages

- apps/website-25/src/components/careers/CareersSection.tsx
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
Update careers JobListing to use new CTAButton
| 📸 |  |
| 🖥️ | <img width="1512" alt="image" src="https://github.com/user-attachments/assets/d2dd8a91-cf57-494a-9140-e4c1eaed07f9" /> |
| 📱  |  |
```
Time:    1.372s 
```
> Update careers JobListing to use new CTAButton

- apps/website-25/src/components/homepage/GraduateSection.tsx
- apps/website-25/src/components/homepage/__snapshots__/GraduateSection.test.tsx.snap
Add FaceTiles component to Graduate section
Related to #69  (issue)
Add FaceTiles component to Graduate section - alt tags could be more descriptive
| 📸 |  |
|-----
----|---|
| 🖥️ |  |
| 📱  |  |
```
@bluedot/website-25:test:  Test Files  10 passed (10)
@bluedot/website-25:test:       Tests  11 passed (11)
@bluedot/website-25:test:    Start at  11:35:15
@bluedot/website-25:test:    Duration  1.58s (transform 244ms, setup 1ms, collect 6.29s, tests 148ms, environment 1.70s, prepare 705ms)
```
> Add FaceTiles component to Graduate section

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- libraries/ui/src/Section.test.tsx
- libraries/ui/src/Section.tsx
- libraries/ui/src/__snapshots__/Section.test.tsx.snap
Update Section component to include optional CTALinkOrButton
Fixes #51  (issue)
| 📸 |  |
| 🖥️ | 
|
| 📱  |  |
```
@bluedot/website-25:test:  Test Files  10 passed (10)
@bluedot/website-25:test:       Tests  11 passed (11)
@bluedot/website-25:test:    Start at  13:20:01
@bluedot/website-25:test:    Duration  1.71s (transform 282ms, setup 0ms, collect 5.58s, tests 136ms, environment 3.23s, prepare 887ms)
```
> Update Section component to include optional CTALinkOrButton

- apps/website-25/src/pages/_app.tsx
- libraries/ui/src/Nav.test.tsx
- libraries/ui/src/Nav.tsx
- libraries/ui/src/__snapshots__/Nav.test.tsx.snap
Add Explore Dropdown Menu
Fixes #92 
| 📸 |  |
| 🖥️ |
|
| 📱  |  |
```
@bluedot/website-25:test:  Test Files  10 passed (10)
@bluedot/website-25:test:       Tests  11 passed (11)
@bluedot/website-25:test:    Start at  15:03:33
@bluedot/website-25:test:    Duration  1.77s (transform 309ms, setup 0ms, collect 6.24s, tests 147ms, environment 2.31s, prepare 1.44s)
```
> Add Explore Dropdown Menu

- apps/website-25/src/components/homepage/StorySection.tsx
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- apps/website-25/src/globals.css
- apps/website-25/src/pages/_app.tsx
Update nav links
- Added "Support us" link
- Added "Blog" link
- Updated global default link styles
- Add links in StorySection
| 📸 |  |
https://github.com/user-attachments/assets/e08db9c2-6802-4196-b102-171344a862f3
```
Time:    1.56s ```
> Update nav links

- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/pages/careers.tsx
Update careers page to use ValueCard
Related to #104  (issue)
| 📸 |  |
| 🖥️ |
|
| 📱  |  |
```
@bluedot/website-25:test:  Test Files  10 passed (10)
@bluedot/website-25:test:       Tests  11 passed (11)
@bluedot/website-25:test:    Start at  14:20:55
@bluedot/website-25:test:    Duration  1.87s (transform 308ms, setup 0ms, collect 7.08s, tests 187ms, environment 1.67s, prepare 784ms)
```
> Update careers page to use ValueCard

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/JoinUsCta.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- apps/website-25/src/globals.css
- libraries/ui/src/Banner.tsx
- libraries/ui/src/CTALinkOrButton.test.tsx
- libraries/ui/src/CTALinkOrButton.tsx
- libraries/ui/src/Footer.tsx
- libraries/ui/src/__snapshots__/Banner.test.tsx.snap
- libraries/ui/src/__snapshots__/CTALinkOrButton.test.tsx.snap
- libraries/ui/src/__snapshots__/Card.test.tsx.snap
- libraries/ui/src/__snapshots__/Footer.test.tsx.snap
- libraries/ui/src/__snapshots__/Section.test.tsx.snap
Add .link-on-dark
- Noticed we needed support for links on dark background
- Update CTALinkorButton to use new styles
- Update Footer links to use new styles
- Update Banner submit btn to use CTALinkorButton
- https://github.com/user-attachments/assets/34615f74-69b1-4f6d-818c-aca4181a1b0c
```
Time:    1.831s 
```
> Add .link-on-dark

- apps/storybook/.storybook/main.ts
Disable storybook telemetry
See https://storybook.js.org/docs/configure/telemetry
```
Time:    3.167s 
```
> Disable storybook telemetry

- apps/website-25/src/components/about/HistorySection.stories.tsx
- libraries/ui/src/Banner.stories.tsx
- libraries/ui/src/CTALinkOrButton.stories.tsx
- libraries/ui/src/ValueCard.stories.tsx
Add some stories for testing
Added some new stories for...
1. `CtaLinkOrButton`
2. `HistorySection`
3. `ValueCard`
4. `Banner`
Used a Lewis Carrol generator for the test text: https://www.happycow.org.uk/inspiration/quotes_carroll_random.shtml
https://github.com/user-attachments/assets/4602e027-0e79-4741-80a1-c29ac16ac209
https://github.com/user-attachments/assets/a41cb0a9-bc3a-48b5-86a5-cbbf4b8aef84
```
Time:    1.822s 
```
> Add some stories for testing

- libraries/ui/src/Banner.tsx
- libraries/ui/src/__snapshots__/Banner.test.tsx.snap
- libraries/ui/src/__snapshots__/Footer.test.tsx.snap
Fix Banner bug introduced in #123 
- Update flex styles
```
Time:    978ms 
```
> Fix Banner bug

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
- apps/website-25/src/components/homepage/StorySection.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- libraries/ui/src/Banner.tsx
- libraries/ui/src/Footer.tsx
- libraries/ui/src/Section.tsx
- libraries/ui/src/__snapshots__/Banner.test.tsx.snap
- libraries/ui/src/__snapshots__/Footer.test.tsx.snap
- libraries/ui/src/__snapshots__/Section.test.tsx.snap
Update Section and remove Banner for now
Fixes #151 
```
Time:    2.001s 
```
> Update Section and remove Banner for now

- libraries/ui/src/Nav.tsx
- libraries/ui/src/__snapshots__/Nav.test.tsx.snap
Update Nav buttons
- Temp links for login and get started
- Added BEM classes
- Updated dropdown markup to simplify
- Explore content is still not perfect, but deeming this acceptable for MVP 🚀 
https://github.com/user-attachments/assets/804108f7-bfd6-45df-bdf5-3ded480e2361
```
Time:    2.099s 
```
> Update Nav buttons

- apps/website-25/src/components/about/IntroSection.test.tsx
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/globals.css
- apps/website-25/src/pages/privacy-policy.tsx
- libraries/ui/src/Section.tsx
Add Privacy Policy
- Add Privacy Policy page based on https://bluedot.org/privacy-policy/
- Make title optional for Section
- Update missing arg in IntroSection test
- Fix ul styles
```
```
> Add Privacy Policy page. Update Section for optional title

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/IntroSection.tsx
- apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
- apps/website-25/src/components/homepage/GraduateSection.tsx
- apps/website-25/src/components/homepage/StorySection.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/GraduateSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- libraries/ui/src/Section.tsx
- libraries/ui/src/__snapshots__/Section.test.tsx.snap
- libraries/ui/src/default-config/tailwind.ts
Update Section widths and gutters for new design system
- Quick fixes!
- Move GraduateSection to use Section
- Clean up StorySection, IntroSection styles
- https://tailwindcss.com/docs/responsive-design#customizing-your-theme
```
```
> Update Section widths and gutters for new design system

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/IntroSection.tsx
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/careers/CareersSection.tsx
- apps/website-25/src/components/careers/ValuesSection.test.tsx
- apps/website-25/src/components/careers/ValuesSection.tsx
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/ValuesSection.test.tsx.snap
- apps/website-25/src/components/homepage/CourseSection.tsx
- apps/website-25/src/components/homepage/GraduateSection.tsx
- apps/website-25/src/components/homepage/StorySection.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/GraduateSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- apps/website-25/src/pages/careers.tsx
- libraries/ui/src/Card.tsx
- libraries/ui/src/ValueCard.tsx
- libraries/ui/src/__snapshots__/Card.test.tsx.snap
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
- libraries/ui/src/__snapshots__/ValueCard.test.tsx.snap
Quick mobile layout fixes
- Fix non-responsive images
- Update cards for responsiveness
- Update GraduateSection for scroll (to be replaced with SlideList)
- Rearrange CourseSection for scroll (to be replaced with SlideList)
- Move ValueSection to its own component for consistency
- Remove custom section padding on CareersSection, ValuesSection
| 📸 |  Home  | About |  Careers |
|---|----|---|---|
| 🖥️ | ![localhost_8000_ (4)](https://github.com/user-attachments/assets/cca30aff-6411-41f6-bdcf-9edf92489832) | ![localhost_8000_about (2)](https://github.com/user-attachments/assets/f8ed2277-19ec-409c-971c-1ed8ea89159d) | ![localhost_8000_careers (1)](https://github.com/user-attachments/assets/69940827-4104-4abf-9b15-4213774e1936) |
| 📱 | ![localhost_8000_(iPhone 12 …
> Quick mobile layout fixes

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/BeliefsSection.test.tsx
- apps/website-25/src/components/about/BeliefsSection.tsx
- apps/website-25/src/components/about/HistorySection.tsx
- apps/website-25/src/components/about/TeamSection.tsx
- apps/website-25/src/components/about/__snapshots__/BeliefsSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/pages/about.tsx
- libraries/ui/src/ValueCard.tsx
- libraries/ui/src/__snapshots__/ValueCard.test.tsx.snap
Add Belief Card placeholders
- Use ValueCard to create new BeliefSection. icons and UX TBD ; placeholder for now
- Also removed added padding on HistorySection, TeamSection
```
Time:    2.272s 
```
> Add Belief Card placeholders

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/components/about/HistorySection.tsx
- apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap
Update HistorySection copy
- New website copy from Will
```
Time:    1.763s 
```
> Update HistorySection copy

- apps/frontend-example/next-env.d.ts
- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/TestimonialSection.tsx
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
- apps/website-25/src/components/homepage/CourseSection.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- libraries/ui/src/Card.tsx
- libraries/ui/src/CourseCard.tsx
- libraries/ui/src/SlideList.stories.tsx
- libraries/ui/src/SlideList.test.tsx
- libraries/ui/src/SlideList.tsx
- libraries/ui/src/__snapshots__/Card.test.tsx.snap
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
- libraries/ui/src/default-config/tailwind.ts
- libraries/ui/src/index.ts
Add SlideList component, use it for TestimonialSection and CourseSection
Fixes #106
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
[Demo of homepage](https://www.loom.com/share/e5856eed58d943d7a107ebdb5990a0b5)
[Demo of storybook](https://www.loom.com/share/69ddb0fef3544e6e9fa3e28d3357c790)
```
@bluedot/website-25:test:   Snapshots  2 updated 
@bluedot/website-25:test:  Test Files  14 passed (14)
@bluedot/website-25:test:       Tests  16 passed (16)
@bluedot/website-25:test:    Start at  16:53:42
@bluedot/website-25:test:    Duration  2.35s (transform 323ms, setup 0ms, collect 10.06s, tests 269ms, environment 3.37s, prepare 972ms)
```
> Add SlideList component, use it for TestimonialSection and CourseSection

- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
- apps/website-25/src/components/homepage/CourseSection.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- libraries/ui/src/Card.tsx
- libraries/ui/src/CourseCard.tsx
- libraries/ui/src/SlideList.tsx
- libraries/ui/src/__snapshots__/Card.test.tsx.snap
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
- libraries/ui/src/shared.css
Adding elevated state to CourseCard hover
Fixes #186 
- Add .container-elevated on hover to coursecards
- Tweak some slidelist rendering for desktop based on Project Manager feedback
- Wrapped shared.css in tailwind utilities layer so that it can be picked up for psuedo states like :hover
https://github.com/user-attachments/assets/e8923863-b50f-4cf2-b759-4f48e0a2ae25
https://github.com/user-attachments/assets/ac1c12f1-0e4f-43f0-80af-baff3b6acb24
https://github.com/user-attachments/assets/db130855-b5b0-4297-875f-08a454f4ee2d
```
Cached:    4 cached, 7 total
Time:    2.981s 
```
> Adding elevated state to CourseCard hover

- apps/storybook/.storybook/main.ts
- apps/storybook/package.json
- libraries/ui/src/CTALinkOrButton.stories.tsx
- package-lock.json
See #93
Add `@storybook/addon-designs` with `Link`-story example.
Part of #93.
```
Time:    2.884s 
```
> Add `@storybook/addon-designs`

- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- libraries/ui/src/SlideList.tsx
Update buttons to go back and forth. Add disabled state when at the end
Fixes #184 
| 📸 |  |
| 📕 | [Storybook demo](https://www.loom.com/share/9f72944d7e9b4593a59cf494239557dc?sid=3f4c9556-f4bb-4070-aa0a-3862797e42ae)  |
| 🖥️ | [homepage demo](https://www.loom.com/share/29922114c33e4eb79ca275d395317a1e?sid=fab489d1-93c7-4712-a407-4d1624eff4c8) |
| 📱  |  |
```
@bluedot/website-25:test:  Test Files  14 passed (14)
@bluedot/website-25:test:       Tests  16 passed (16)
@bluedot/website-25:test:    Start at  10:27:55
@bluedot/website-25:test:    Duration  1.89s (transform 272ms, setup 2ms, collect 7.81s, tests 278ms, environment 2.08s, prepare 918ms)
```
> Update SlideList Buttons

- apps/website-25/src/components/homepage/CommunitySection/TestimonialSection.test.tsx
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
- libraries/ui/src/SlideList.test.tsx
- libraries/ui/src/SlideList.tsx
Hide SlideList buttons if both disabled
Fixes #185 
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
```
@bluedot/website-25:test:  Test Files  14 passed (14)
@bluedot/website-25:test:       Tests  17 passed (17)
@bluedot/website-25:test:    Start at  11:34:41
@bluedot/website-25:test:    Duration  1.75s (transform 258ms, setup 1ms, collect 7.90s, tests 251ms, environment 2.14s, prepare 831ms)
```
> Hide SlideList buttons if both disabled

- apps/website-25/src/components/homepage/__snapshots__/GraduateSection.test.tsx.snap
- apps/website-25/src/pages/_app.tsx
- libraries/ui/src/FaceTiles.tsx
- libraries/ui/src/Nav.tsx
- libraries/ui/src/__snapshots__/FaceTiles.test.tsx.snap
- libraries/ui/src/__snapshots__/Nav.test.tsx.snap
Bug Bash Tweaks: Move Nav links for MVP and update GraduateSection
#204 
- "Support us" will be our primary CTA for MVP
- Update GraduateSection to more rounded number (4000+)
```
```
> Bug Bash Tweaks: Move Nav links for MVP

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/JoinUsCta.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/TestimonialSection.tsx
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/GovernanceProjects.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- libraries/ui/src/CTALinkOrButton.tsx
- libraries/ui/src/__snapshots__/Banner.test.tsx.snap
- libraries/ui/src/__snapshots__/CTALinkOrButton.test.tsx.snap
- libraries/ui/src/__snapshots__/Card.test.tsx.snap
- libraries/ui/src/__snapshots__/CookieBanner.test.tsx.snap
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
- libraries/ui/src/__snapshots__/Nav.test.tsx.snap
- libraries/ui/src/__snapshots__/Section.test.tsx.snap
- libraries/ui/src/default-config/tailwind.ts
Add `rounded-radius` aliases to match Figma Design System.
Fixes #135 
📸 No visual changes
```
Time:    3.444s 
```
> Add design system radius

- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
- apps/website-25/src/components/homepage/CourseSection.test.tsx
- apps/website-25/src/components/homepage/CourseSection.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- libraries/ui/src/SlideList.test.tsx
- libraries/ui/src/SlideList.tsx
Responsive CourseSection for mobile and tablet. Shows 1 slide on mobile and 2 on tablet and desktop.
Fixes #163  (issue)
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
```
@bluedot/ui:test:  Test Files  13 passed (13)
@bluedot/ui:test:       Tests  43 passed (43)
@bluedot/ui:test:    Start at  15:26:39
@bluedot/ui:test:    Duration  975ms (transform 307ms, setup 0ms, collect 2.87s, tests 254ms, environment 2.02s, prepare 833ms)
```
> WIP: Responsive CourseSection

- apps/website-25/src/components/homepage/BlogSection.test.tsx
- apps/website-25/src/components/homepage/BlogSection.tsx
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/BlogSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/pages/index.tsx
- libraries/ui/src/Tag.tsx
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
- libraries/ui/src/__snapshots__/Tag.test.tsx.snap
Add new BlogSection. Update Tag styles.
Resolves #214
- Add new BlogSection
- Static data for now; will be updated to GraphQL calls once TinaCMS is integrated
- Updated Tag styles to the latest
```
Time:    1.734s 
```
> Add new BlogSection. Update Tag styles.

- apps/website-25/src/components/homepage/FAQSection.tsx
- apps/website-25/src/components/homepage/__snapshots__/FAQSection.test.tsx.snap
- libraries/ui/src/Section.tsx
Add contact us section to about page
No issue created yet, related to [this project](https://github.com/orgs/bluedotimpact/projects/2/views/1)
| 📸 |  |
| 📕 |  |
| 🖥️ |
|
| 📱  |  |
```
@bluedot/website-25:test:       Tests  23 passed (23)
@bluedot/website-25:test:    Start at  12:22:46
@bluedot/website-25:test:    Duration  2.96s (transform 461ms, setup 1ms, collect 15.30s, tests 381ms, environment 5.52s, prepare 1.73s)
```
> Update FAQ section title

- libraries/ui/src/Nav.tsx
- libraries/ui/src/__snapshots__/Nav.test.tsx.snap
Change nav color on scroll
No ticket created yet, related to [website project](https://github.com/orgs/bluedotimpact/projects/2/views/1)
| 📸 |  |
| 📕 |  |
| 🖥️ | [Loom](https://www.loom.com/share/b441e593c96143c78970675ec78a2424?sid=fe408c60-ce1e-49b1-bdc2-1b17a1eae95c) |
| 📱  |  |
```
@bluedot/ui:test:  Test Files  14 passed (14)
@bluedot/ui:test:       Tests  45 passed (45)
@bluedot/ui:test:    Start at  12:50:23
@bluedot/ui:test:    Duration  1.54s (transform 403ms, setup 0ms, collect 5.03s, tests 316ms, environment 2.76s, prepare 938ms)
@bluedot/ui:test: 
```
> Change nav color on scroll

- libraries/ui/src/CourseCard.tsx
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
Keep container on CourseCard hover
No issue created yet, but related to [website MVP](https://github.com/orgs/bluedotimpact/projects/2/views/1)
| 📸 |  |
| 📕 |  |
| 🖥️ | [Loom](https://www.loom.com/share/64d1b6368196489ea1fecc0bb1e8f876?sid=20b85926-0920-42d7-aa91-8ccb96285633) |
| 📱  |  |
```
@bluedot/ui:test:   Snapshots  2 updated 
@bluedot/ui:test:  Test Files  14 passed (14)
@bluedot/ui:test:       Tests  45 passed (45)
@bluedot/ui:test:    Start at  08:39:40
@bluedot/ui:test:    Duration  1.31s (transform 399ms, setup 0ms, collect 3.01s, tests 366ms, environment 2.29s, prepare 1.03s)
@bluedot/ui:test: 
```
> Keep container on CourseCard hover

- apps/website-25/.eslintrc.js
- apps/website-25/eslint-local-rules.js
- apps/website-25/package.json
- apps/website-25/src/components/homepage/CommunitySection/GovernanceProjects.tsx
- apps/website-25/src/components/homepage/CommunitySection/TestimonialSection.tsx
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/GovernanceProjects.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
- package-lock.json
Add linting rule for [design system](https://oliviamcgoffi-iwn5117.slack.com/archives/C089CN67W9L/p1738863847038509) and update non-compliant files
No issue created, but related to [website MVP](https://github.com/orgs/bluedotimpact/projects/2/views/1) and [updated design system](https://oliviamcgoffi-iwn5117.slack.com/archives/C089CN67W9L/p1738863847038509)
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
```
@bluedot/website-25:test:       Tests  23 passed (23)
@bluedot/website-25:test:    Start at  10:01:26
@bluedot/website-25:test:    Duration  2.34s (transform 348ms, setup 0ms, collect 11.16s, tests 374ms, environment 3.88s, prepare 1.54s)
```
> Add linting rule for design system and update non-compliant files

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/BeliefsSection.tsx
- apps/website-25/src/components/about/HistorySection.tsx
- apps/website-25/src/components/about/IntroSection.tsx
- apps/website-25/src/components/about/__snapshots__/BeliefsSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/components/careers/CareersSection.tsx
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/GovernanceProjects.tsx
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/GovernanceProjects.test.tsx.snap
- apps/website-25/src/components/homepage/StorySection.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- apps/website-25/src/pages/_app.tsx
- libraries/ui/src/Card.stories.tsx
- libraries/ui/src/CourseCard.tsx
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
Bug Bash Tweaks: Copy update and revise external links
Fixes #219
- Misc. copy updates
- AISF URLs are no longer being treated as external links. Update everywhere.
- Weirdly, CourseCard lint tests were failing because 2 props were mistakenly considered unused. Added eslint disable to resolve for now.
```
```
> Bug Bash Tweaks: copy update and revise external links

- apps/website-25/src/pages/about.tsx
- apps/website-25/src/pages/careers.tsx
- apps/website-25/src/pages/index.tsx
Add metadata to home, about, and careers pages
Fixes #245  (issue)
Add metadata to home, about, and careers pages
| 📸 |  |
| 📕 |  |
| 🖥️ | 
|
| 📱  |  |
```
@bluedot/website-25:test:    Start at  14:24:04
@bluedot/website-25:test:    Duration  2.27s (transform 380ms, setup 1ms, collect 11.19s, tests 370ms, environment 3.57s, prepare 1.21s)
```
> Add metadata to home, about, and careers pages

- apps/website-25/package.json
- apps/website-25/src/pages/_app.tsx
- libraries/ui/src/Nav.tsx
- libraries/ui/src/index.ts
Bold current page on nav
Fixes #247  (issue)
Bold current page on nav
| 📸 |  |
| 📕 |  |
| 🖥️ | [Loom](https://www.loom.com/share/6fbaa70d72d848c69b06070d85769333?sid=56b907c9-217f-4bde-a15d-42866da7951b) |
| 📱  |  |
```
@bluedot/website-25:test:    Start at  17:07:32
@bluedot/website-25:test:    Duration  2.81s (transform 363ms, setup 1ms, collect 13.21s, tests 397ms, environment 5.09s, prepare 1.66s)
```
> Bold current page on nav

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/HistorySection.tsx
- apps/website-25/src/components/about/IntroSection.tsx
- apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
- apps/website-25/src/components/homepage/CourseSection.tsx
- apps/website-25/src/components/homepage/StorySection.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- libraries/ui/src/Banner.tsx
- libraries/ui/src/Card.tsx
- libraries/ui/src/CookieBanner.tsx
- libraries/ui/src/CourseCard.tsx
- libraries/ui/src/__snapshots__/Banner.test.tsx.snap
- libraries/ui/src/__snapshots__/Card.test.tsx.snap
- libraries/ui/src/__snapshots__/CookieBanner.test.tsx.snap
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
Use space-between values
- Update gaps to use the design system standard `[x]-space-between`
```
Time:    3.036s 
```
> Use space-between values

- apps/website-25/src/components/homepage/FAQSection.tsx
- apps/website-25/src/components/homepage/__snapshots__/FAQSection.test.tsx.snap
Update faq-section to force not scrolling on mobile
No issue, 🐛 related to [website MVP](https://github.com/orgs/bluedotimpact/projects/2/views/1)
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  | [0:09-0:11 in Loom](https://www.loom.com/share/1f768ede14e742558bc7640c23e87a28) |
```
@bluedot/website-25:test:    Start at  09:02:58
@bluedot/website-25:test:    Duration  2.71s (transform 357ms, setup 0ms, collect 11.16s, tests 411ms, environment 4.51s, prepare 1.79s)
```
> Update faq-section to force not scrolling on mobile

- apps/website-25/src/pages/_app.tsx
Add governance in depth course to nav
Fixes #280
| 📸 |  |
| 📕 |  |
| 🖥️ |
|
| 📱  |  |
```
@bluedot/website-25:test:    Start at  09:18:55
@bluedot/website-25:test:    Duration  3.11s (transform 442ms, setup 0ms, collect 11.21s, tests 388ms, environment 5.09s, prepare 2.18s)
```
> Add governance in depth course to nav

- libraries/ui/src/Footer.tsx
- libraries/ui/src/__snapshots__/Footer.test.tsx.snap
Update footer links
Fixes #279  (issue)
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
```
@bluedot/website-25:test:    Start at  09:24:39
@bluedot/website-25:test:    Duration  2.32s (transform 411ms, setup 2ms, collect 11.21s, tests 372ms, environment 4.68s, prepare 1.76s)
```
> Update footer links

- apps/website-25/src/components/homepage/CommunitySection/TestimonialSection.tsx
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
Update testimonial section to match [design](https://www.figma.com/design/s4dNR4ELGKPbja6GkHLVJy/Website-Laura's-Working-File?node-id=744-2413&t=qXKXlSFKtAnb1KQ0-0)
Fixes #282 
Updates the quote size -> 14px, author size -> 16px, role -> 12px
| 📸 |  |
| 📕 |  |
| 🖥️ | 
|
| 📱  |  |
```
@bluedot/website-25:test:    Start at  09:49:56
@bluedot/website-25:test:    Duration  3.79s (transform 537ms, setup 0ms, collect 19.22s, tests 456ms, environment 4.67s, prepare 2.14s)
```
> Update testimonial section to match designs

- libraries/ui/src/Footer.tsx
- libraries/ui/src/__snapshots__/Footer.test.tsx.snap
Update gap in footer columns and between links
Fixes #278 
Update gap in footer columns and between links
| 📸 |  |
| 📕 |  |
| 🖥️ | 
|
| 📱  |  |
```
@bluedot/website-25:test:    Start at  09:57:55
@bluedot/website-25:test:    Duration  2.75s (transform 417ms, setup 1ms, collect 11.94s, tests 379ms, environment 4.67s, prepare 1.63s)
```
> Update gap in footer columns and between links

- libraries/ui/src/Footer.tsx
- libraries/ui/src/__snapshots__/Footer.test.tsx.snap
> ui: Add missing footer link to BlueDot logo

- libraries/ui/src/Footer.tsx
- libraries/ui/src/__snapshots__/Footer.test.tsx.snap
Currently the footer has many visual problems (#303, #305, #308, #287, #278, #332). This attempts to fix all of them for the various viewpoints, bringing all the dimensions to the Figma spec and having reasonable interpolation between them.
Fixes #303, fixes #305, fixes #308, fixes #287, fixes #278, fixes #332
> footer: Fix to Figma spec with reasonable interpolation

- apps/website-25/src/components/homepage/__snapshots__/FAQSection.test.tsx.snap
- libraries/ui/src/Collapsible.test.tsx
- libraries/ui/src/Collapsible.tsx
- libraries/ui/src/__snapshots__/Collapsible.test.tsx.snap
Replace implementation of Collapsible with a standard `<details>` and `<summary>` elements which makes the code simpler and the element more accessible (and useful to other users, e.g. being easier for people using Cmd+F or for LLMs to realise it's relevant content).
Fixes #337, partly addresses #286
- NB: this does remove the open/closed states, which weren't being used anyway
(no visual changes)
> website: Improve accessibility of collapsible component

- apps/website-25/src/components/homepage/CourseSection.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/lib/utmParams.test.ts
- apps/website-25/src/lib/utmParams.ts
Enable CTR tracking for clicks on course cards.
Fixes #276.
* Add `utmParams` helper
* Use on `CourseCards`
```
Time:    5.33s 
```
> Add `utm` tracking for `CourseSection`

- apps/website-proxy/src/nginx.template.conf
> website-proxy: invert proxy setup so it defaults to old site

- apps/website-25/src/components/homepage/BlogSection.tsx
- apps/website-25/src/components/homepage/__snapshots__/BlogSection.test.tsx.snap
> website: BlogSection: Add spacing between blog date and title

- apps/website-25/src/pages/privacy-policy.tsx
Aligns the styling with the Figma 'Generic Page' spacing, and simplifies the code.
Fixes #290
> website: Fix privacy policy styling

- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- libraries/ui/src/CourseCard.tsx
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
- libraries/ui/src/constants.ts
Fixes #375
(NB: have put 9 weeks instead of the 7 weeks requested on the ticket, because this is the correct length - I think we got it wrong earlier)
> website: Update econ of TAI card metadata

- libraries/ui/src/Nav.tsx
- libraries/ui/src/__snapshots__/Nav.test.tsx.snap
https://github.com/user-attachments/assets/1e637584-48e7-4ee8-9f96-5796be1060f0
Fixes # (issue)
| 📸 |  |
| 📕 |  |
| 🖥️ | ![Screenshot 2025-02-14 at 09 17 22](https://github.com/user-attachments/assets/cc3fbece-a431-4581-bba2-61c59487837c) |
| 📱  |  |
```
Time:    1.854s
```
> Center header navigation

- libraries/ui/src/SlideList.tsx
https://github.com/user-attachments/assets/e89c88c2-38d5-4174-932a-7568a7c55de7
#286 (addresses one part of this)
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
```
Cached:    7 cached, 7 total
Time:    279ms >>> FULL TURBO
```
> Handle tab scrolling in SlideList

- libraries/ui/src/CourseCard.tsx
- libraries/ui/src/SlideList.tsx
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
Fixes #367 
| 📸 |  |
| 📕 |  |
| 🖥️ | ![Screenshot 2025-02-14 at 11 03 51](https://github.com/user-attachments/assets/13e99e7d-7d45-4ceb-8429-e1a541fa2438) |
| 📱  | ![Screenshot 2025-02-14 at 11 08 10](https://github.com/user-attachments/assets/c7e638c7-5548-4a52-beab-b3d3e66ef9a0) |
```
Time:    1.841s
```
> Align featured course card with carousel

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/BeliefsSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/ValuesSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/CommunityValuesSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/ProjectsSubSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/ValuesSection.test.tsx.snap
- apps/website-25/src/components/homepage/CourseSection.tsx
- apps/website-25/src/components/homepage/FAQSection.tsx
- apps/website-25/src/components/homepage/StorySection.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/FAQSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- apps/website-25/src/pages/index.tsx
[Homepage] Update to final website content
#376 
- Update Hero, Our Courses, About Us, and FAQ
```
Time:    3.748s 
```
> [Homepage] Update to final website content

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/BeliefsSection.tsx
- apps/website-25/src/components/about/HistorySection.tsx
- apps/website-25/src/components/about/IntroSection.tsx
- apps/website-25/src/components/about/__snapshots__/BeliefsSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/components/careers/CultureSection.test.tsx
- apps/website-25/src/components/careers/CultureSection.tsx
- apps/website-25/src/components/careers/ValuesSection.tsx
- apps/website-25/src/components/careers/__snapshots__/CultureSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/ValuesSection.test.tsx.snap
- apps/website-25/src/components/homepage/StorySection.tsx
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- apps/website-25/src/pages/_app.tsx
- apps/website-25/src/pages/about.tsx
- apps/website-25/src/pages/careers.tsx
Update to final website content on /about and /careers pages
- Updated copy
- Created new CultureSection to reflect the new section inclusion. Image is **only a placeholder** for now and will be greatly changed when assets are ready by EOD
#376
> [About Us] [Join us] Update to final website content

- .vscode/extensions.json
- README.md
- apps/infra/README.md
- apps/infra/src/k8s/serviceDefinitions.ts
- apps/infra/src/k8s/services.ts
Various small tidy ups to better explain how apps get deployed, as well as simplify the process of creating new apps.
> infra+devdocs: minor tidy ups

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/IntroSection.tsx
- apps/website-25/src/components/about/TeamSection.tsx
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/careers/CultureSection.tsx
- apps/website-25/src/components/careers/__snapshots__/CultureSection.test.tsx.snap
- apps/website-25/src/components/homepage/BlogSection.tsx
- apps/website-25/src/components/homepage/CommunitySection/TestimonialSection.tsx
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/BlogSection.test.tsx.snap
- libraries/ui/src/default-config/tailwind.css
Final nitpicks!!!!
Fixes #405  
Fixes #407 
Final nitpicks!!!!
```
Final nitpicks!!!!
```
> Final nitpicks!!!!

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/pages/about.tsx
- libraries/ui/src/HeroSection.tsx
Add hero mini title
Fixes #398 
| 📸 |  |
| 📕 |  |
| 🖥️ | <!
-- Include a **Desktop** screenshot or screen recording demonstrating your change--> |
| 📱  |  |
```
@bluedot/website-25:test:  Test Files  21 passed (21)
@bluedot/website-25:test:       Tests  29 passed (29)
@bluedot/website-25:test:    Start at  13:34:22
@bluedot/website-25:test:    Duration  4.33s (transform 764ms, setup 0ms, collect 16.04s, tests 560ms, environment 6.72s, prepare 4.33s)
```
> Add hero mini title

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/pages/about.tsx
- apps/website-25/src/pages/careers.tsx
Mini Header to Join page too
Also fixed title tags
```
```
> Mini Header to Join page too

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/BeliefsSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/HistorySection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/IntroSection.test.tsx.snap
- apps/website-25/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/CareersSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/CultureSection.test.tsx.snap
- apps/website-25/src/components/careers/__snapshots__/ValuesSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/CommunityValuesSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/ProjectsSubSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/TestimonialSection.test.tsx.snap
- apps/website-25/src/components/homepage/CommunitySection/__snapshots__/ValuesSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/BlogSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/FAQSection.test.tsx.snap
- apps/website-25/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- libraries/ui/src/Section.stories.tsx
- libraries/ui/src/Section.tsx
- libraries/ui/src/__snapshots__/Section.test.tsx.snap
Fixes #446 
| 📸 |  |
| 📕 | ![Screenshot 2025-02-18 at 09 19 26](https://github.com/user-attachments/assets/ec62f0ce-a1d2-42ee-8daa-8fafdc750a25) |
| 🖥️ | ![Screenshot 2025-02-18 at 09 20 35](https://github.com/user-attachments/assets/fa877bd6-0282-4071-9d31-ad92d3b0c875) |
| 📱  | ![Screenshot 2025-02-18 at 09 21 13](https://github.com/user-attachments/assets/b4bc8e15-8296-4690-92de-dc08f75e4b7b) |
```
Time:    4.603s
```
cc @vioricagh
> Tweak section heading alignment

- apps/website-proxy/src/nginx.template.conf
Point `bluedot.org` to `website-25-production` 🎉
Following up on #460
> website-proxy: Point to `website-25-production` 🎉

- .github/workflows/ci_cd.yaml
Follow up on #464, see https://github.com/bluedotimpact/bluedot/actions/runs/13433527807/job/37530588449.
> Actually force deploy of `website-proxy` 😇

- .github/workflows/ci_cd.yaml
Revert quick fix.
We'll address this after the staging rollout.
Following up on #465 & #464.
> ci_cd: Revert "force deploy of `website-proxy`"

- apps/website-25/.env.staging.template
- libraries/docker-scripts/src/multistage/deploy-staging.sh
Disallow indexing & update tracking keys.
Following up on #460.
> website-25(staging): Disallow indexing & update tracking keys

- .github/workflows/ci_cd.yaml
This reverts commit 9d3a0f5e96922192825202320825b1d91aa06c2f, see #470.
> Revert "Force deploy of `website-25`"

- libraries/ui/src/Footer.tsx
- libraries/ui/src/__snapshots__/Footer.test.tsx.snap
From [issue](https://github.com/bluedotimpact/bluedot/issues/447):
> Remove Resources and move Privacy Policy under BlueDot Impact
cc @vioricagh to confirm this looks right
Fixes #447 
| 📸 |  |
| 📕 | ![Screenshot 2025-02-18 at 22 22 50](https://github.com/user-attachments/assets/d05a71f5-6fd5-454d-ab01-9c8da1072031) |
| 🖥️ | ![Screenshot 2025-02-18 at 22 19 17](https://github.com/user-attachments/assets/d6d88ef0-4b5e-46cd-9018-b06e8deae1c6) |
| Tablet | ![Screenshot 2025-02-18 at 22 19 29](https://github.com/user-attachments/assets/9a4ab249-c1d1-47d0-8712-47cc5f282ae3) |
| 📱  | ![Screenshot 2025-02-18 at 22 19 58](https://github.com/user-attachments/assets/6d7a9463-2607-4a76-9352-c75051a1d9cf) |
```
Cached:    6 cached, …
```
> Remove resources column in footer

- apps/website-25/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website-25/src/__tests__/pages/__snapshots__/careers.test.tsx.snap
- apps/website-25/src/lib/routes.ts
- apps/website-25/src/pages/index.tsx
`<title>` unchanged:
Fixes #479 
_Foregoing the usual screenshots as this is a simple change_
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
```
Time:    6.382s
```
> Change home breadcrumb title to Home

- apps/infra/Pulumi.prod.yaml
- apps/infra/src/k8s/secrets.ts
- apps/infra/src/k8s/serviceDefinitions.ts
- apps/room/src/lib/api/db.ts
Followup from #490, to actually deploy the app.
> infra: Add room

- README.md
- apps/storybook/README.md
- libraries/ui/README.md
- Add storybook link
- Add libraries/ui README
- Minor tweaks to help LLMs parse the READMEs
> docs: Improve READMEs

- libraries/ui/src/utils/makeMakeApiRoute.test.ts
- libraries/ui/src/utils/makeMakeApiRoute.ts
- Mostly adds tests for makeMakeApiRoute
- Discovered a couple typing improvements I could make
> ui: Improve and add tests for makeMakeApiRoute

- apps/website-25/src/components/Nav.tsx
Establish conditionals in Nav
- Add customization for primary CTA
- Add "Login" as secondary CTA
```
Tasks:    10 successful, 10 total
Cached:    9 cached, 10 total
Time:    2.538s 
```
> Reusable Nav

- apps/website-25/src/components/lander/BlueHeader.tsx
- apps/website-25/src/components/lander/Container.tsx
- apps/website-25/src/components/lander/CourseUnitsSection.tsx
- apps/website-25/src/components/lander/FeaturesSection.tsx
- apps/website-25/src/components/lander/LandingPageBase.tsx
- apps/website-25/src/components/lander/NewNav.tsx
- apps/website-25/src/components/lander/SingleTestimonialSection.tsx
- apps/website-25/src/pages/lander/another.tsx
- apps/website-25/src/pages/lander/classic.tsx
- apps/website-25/src/pages/lander/index.tsx
- Move stuff into reusable composable components so it's less chaos when others edit the copy in GitHub later
- Add another variant
> Refactor landing

- apps/website-25/src/components/lander/LandingPageBase.tsx
- apps/website-25/src/components/lander/getCtaUrl.ts
- apps/website-25/src/pages/lander/LandingHero.tsx
- apps/website-25/src/pages/lander/another.tsx
- apps/website-25/src/pages/lander/classic.tsx
- apps/website-25/src/pages/lander/index.tsx
- apps/website-25/src/pages/lander/new-hero.tsx
New LandingHero component
Moving quickly under changing requirements.
[ ] Jest test coverage
[ ] Mobile updates
[ ] Robust testing for different variants
```
```
> New LandingHero component

- apps/website-25/src/components/lander/SingleTestimonialSection.tsx
- apps/website-25/src/pages/lander/LandingHero.tsx
- apps/website-25/src/pages/lander/fing_awesome.tsx
- apps/website-25/src/pages/lander/index.tsx
> Rename to fing_awesome, fix mobile Testimonial, tweak LandingHero

- apps/website-25/src/pages/lander/everyone_community.tsx
- apps/website-25/src/pages/lander/everyone_voice.tsx
- apps/website-25/src/pages/lander/index.tsx
- apps/website-25/src/pages/lander/jobs_optional_learn_skills.tsx
- apps/website-25/src/pages/lander/jobs_optional_save_time.tsx
Subtitle doesn't look great with all variants. Need to revisit styles.
> Add all variants

- apps/website-25/src/pages/lander/LandingHero.tsx
https://github.com/user-attachments/assets/11e45246-9c3c-48d9-b2ba-6af4074efa85
https://github.com/user-attachments/assets/bb990a1f-bf4f-4890-b804-c5b2549a4d05
> Typography tweaks for mobile screens

- apps/website-25/src/components/lander/LandingPageBase.tsx
> Update unit section CTA

- apps/website-25/src/components/lander/LandingPageBase.tsx
> Update Unit content

- apps/website-proxy/src/nginx.template.conf
Enable traffic to the landing pages via website-proxy
> website-proxy: deploy landing pages

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/extensions.json
- README.md
Fixes #248
Tested on macOS and Linux as much as I can so far. Still need to test the full setup script on a new user.
> devex: Add devcontainer configuration, update dev docs

- apps/frontend-example/src/pages/adam.tsx
frontend-example: Add exclamation mark to adam's page
Adam's page is really cool. But it's missing the punctuation to express that. This change fixes that.
> frontend-example: Add exclamation mark to adam's page

- README.md
docs: Update README.md for better colima setup
Main change is bumping the memory, and doing this before brew does things
> docs: Update README.md for better colima setup

- apps/website-25/src/components/lander/BlueH2.tsx
- apps/website-25/src/components/lander/ClassicHero.tsx
- apps/website-25/src/components/lander/CourseUnits.tsx
- apps/website-25/src/components/lander/Features.tsx
- apps/website-25/src/components/lander/LandingPageBase.tsx
- apps/website-25/src/components/lander/NewNav.tsx
- apps/website-25/src/components/lander/SingleTestimonial.tsx
- apps/website-25/src/pages/lander/classic.tsx
website-25: lander: Create reusable ClassicHero component, make other reusable components namespaced
Intended to make it easier for less technical contributors to be able to tweak and copy the lander pages with reduced code duplication.
[no visual changes]
> website-25: lander: Create reusable ClassicHero component, make other reusable components namespaced

- apps/website-25/src/components/courses/UnitLayout.test.tsx
- apps/website-25/src/components/courses/UnitLayout.tsx
- apps/website-25/src/components/courses/__snapshots__/SideBar.test.tsx.snap
- apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
- apps/website-25/src/lib/routes.ts
- apps/website-25/src/pages/courses/future-of-ai/units/2.tsx
- apps/website-25/src/pages/courses/future-of-ai/units/3.tsx
- apps/website-25/src/pages/courses/future-of-ai/units/4.tsx
- libraries/ui/src/constants.ts
Create a UnitLayout component to standardize a template
Fixes #584 
Create a UnitLayout template for standardized course views and populate remaining units for FOAI
```
```
> Create a UnitLayout component to standardize a template

- apps/website-25/src/components/courses/SideBar.tsx
- apps/website-25/src/components/courses/UnitLayout.tsx
- apps/website-25/src/components/courses/__snapshots__/SideBar.test.tsx.snap
- apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
Update max content width
Li-lian Figma feedback
```
```
> Update max content width

- apps/website-25/src/lib/api/db/tables.ts
- apps/website-25/src/pages/api/units.ts
Initial API config for Unit.
See: http://bluedot.org/api/units
> Initial API config for Unit

- .github/workflows/ci_cd.yaml
- .github/workflows/website_deploy_production.yaml
- apps/infra/Pulumi.prod.yaml
- apps/infra/README.md
- apps/infra/src/k8s/secrets.ts
- apps/infra/src/k8s/serviceDefinitions.ts
- apps/infra/src/k8s/services.ts
- libraries/docker-scripts/README.md
- libraries/docker-scripts/src/deploy.sh
- libraries/docker-scripts/src/multistage/deploy-production.sh
- libraries/docker-scripts/src/multistage/deploy-staging.sh
Pushing images to Vultr Container Registry keeps resulting in 504s. We're going to try to switch to GitHub container registry to see if this improves things.
Fixes #473
> infra: Migrate from Vultr Container Registry to GitHub Container Registry

- apps/website-25/src/components/courses/Congratulations.stories.tsx
- apps/website-25/src/components/courses/Congratulations.test.tsx
- apps/website-25/src/components/courses/Congratulations.tsx
- apps/website-25/src/components/courses/SocialShare.stories.tsx
- apps/website-25/src/components/courses/SocialShare.test.tsx
- apps/website-25/src/components/courses/SocialShare.tsx
- apps/website-25/src/components/courses/UnitLayout.test.tsx
- apps/website-25/src/components/courses/UnitLayout.tsx
- apps/website-25/src/components/courses/__snapshots__/Congratulations.test.tsx.snap
- apps/website-25/src/components/courses/__snapshots__/SocialShare.test.tsx.snap
- apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
Add SocialShare component
Fixes #567 
- Add simple SocialShare component
- Use react-icons
- Optional args for course URL, referral code, and pre-filled text
```
```
> Add SocialShare component

- apps/website-25/src/components/courses/UnitLayout.test.tsx
- apps/website-25/src/components/courses/UnitLayout.tsx
- apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
- libraries/ui/src/CTALinkOrButton.test.tsx
- libraries/ui/src/CTALinkOrButton.tsx
- libraries/ui/src/__snapshots__/CTALinkOrButton.test.tsx.snap
Add Previous Unit and Back to Course CTAs
Fixes #637 
```
```
> Add Previous Unit and Back to Course CTAs

- apps/website-25/src/lib/api/db/tables.ts
- apps/website-25/src/pages/api/users/me.ts
- apps/website-25/src/pages/login/clear.tsx
- apps/website-25/src/pages/login/index.tsx
- apps/website-25/src/pages/login/oauth-callback.tsx
- apps/website-25/src/pages/profile.tsx
Adds login and logout pages, as well as an extremely basic profile page (just spits out user info as JSON - will clearly need more work!)
Fixes #570
https://github.com/user-attachments/assets/d0c2c287-3518-4013-aeef-bd529aef79c3
(NB: The error that flashes for a second after login only shows in dev mode, because react in development mode loads the component twice. The oauth library clears the state on the first component load (I believe for security reasons?), resulting in the error message. In practice this does not cause issues.)
> website: Add login flow and extremely basic profile page

- apps/website-25/src/components/courses/SocialShare.test.tsx
- apps/website-25/src/components/courses/SocialShare.tsx
- apps/website-25/src/components/courses/__snapshots__/SocialShare.test.tsx.snap
Fixes #646
| 📸 |  |
| 📕 |  |
| 🖥️ |  |
| 📱  |  |
```
Tasks:    13 successful, 13 total
Cached:    12 cached, 13 total
Time:    7.66s
```
> Test referral code appears in share urls

- apps/website-25/src/components/AnnouncementBanner.stories.tsx
- apps/website-25/src/components/AnnouncementBanner.test.tsx
- apps/website-25/src/components/AnnouncementBanner.tsx
- apps/website-25/src/pages/_app.tsx
Adds an announcement banner for highlighting upcoming events / recent news etc.
Fixes #655
https://github.com/user-attachments/assets/7b7e64d1-7233-42bf-993e-a3240211532a
> website: Add AnnouncementBanner component for announcing events

- apps/website-25/src/components/Nav.stories.tsx
- apps/website-25/src/components/Nav.test.tsx
- apps/website-25/src/components/Nav.tsx
- apps/website-25/src/components/__snapshots__/Nav.test.tsx.snap
- apps/website-25/src/lib/routes.ts
- apps/website-25/src/pages/profile.tsx
- libraries/ui/src/IconButton.stories.tsx
- libraries/ui/src/IconButton.tsx
Fixes #644
- Punted to #650 
| 📸 |  |
| 📕 | ![Screenshot 2025-04-16 at 10 19 18](https://github.com/user-attachments/assets/bf1aa3c2-4688-4df3-90f9-20eb1d0789d4) |
| 🖥️ | ![Screenshot 2025-04-16 at 10 14 55](https://github.com/user-attachments/assets/6c29e874-3d6e-4347-b854-f6cff4ebf357) |
| | ![Screenshot 2025-04-16 at 10 15 07](https://github.com/user-attachments/assets/83576b2c-f632-4502-b9cf-df7f70be4392) |
| | ![Screenshot 2025-04-16 at 10 15 12](https://github.com/user-attachments/assets/267536e4-845f-4ce9-a3b7-dd10225f6477) |
| 📱  | ![Screenshot 2025-04-16 at 10 18 11](https://github.com/user-attachments/assets/17048120-fbe7-4808-9803-63e79b0e14fb) |
| | ![Screenshot 2025-04-16 at 10 18 17](https://github.com/user-attachments/assets/df9b54c3-2311-4c87-b3a2-79f5326b73 …
> Update Nav for logged-in users

- apps/website-proxy/src/nginx.template.conf
> website-25: Add routing for contact page

- apps/login/tools/getBluedotKeycloakTheme.sh
login: Update theme to new design system
Also see https://github.com/bluedotimpact/bluedot-keycloak-theme/pull/2
Fixes #594
See https://github.com/bluedotimpact/bluedot-keycloak-theme?tab=readme-ov-file
Tested locally, with all key flows working (see screenshots above)
> login: Update theme to new design system

- apps/website-25/src/components/Nav.tsx
- apps/website-25/src/components/courses/exercises/FreeTextResponse.tsx
- apps/website-25/src/components/courses/exercises/MultipleChoice.tsx
- apps/website-25/src/components/courses/exercises/__snapshots__/FreeTextResponse.test.tsx.snap
- apps/website-25/src/components/courses/exercises/__snapshots__/MultipleChoice.test.tsx.snap
- apps/website-25/src/lib/routes.ts
- apps/website-25/src/pages/profile.tsx
Update to use centralized login and logout routes
- Adds login to ROUTES
- Update hard-coded /login and /login/clear to reference this constant
TODO: Add query params for redirect URLs
```
```
> Update to use centralized login and logout routes

- apps/infra/Pulumi.prod.yaml
- apps/infra/src/k8s/secrets.ts
- apps/infra/src/k8s/serviceDefinitions.ts
- apps/login/Dockerfile
- apps/login/package.json
Update keycloak version to get:
- security updates
- performance improvements
Tried to follow https://www.keycloak.org/docs/latest/upgrading/index.html closely, and tested it ran locally. But some of the config there is quite complex, so while I'm fairly confident this is correct I'm not 100%. I think we should do this before we go live so that if there is an issue it's not affecting real users badly.
Fixes #679
> login: Update keycloak version

- apps/website-25/src/components/homepage/CourseSection.test.tsx
- apps/website-25/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- libraries/ui/src/__snapshots__/Footer.test.tsx.snap
- libraries/ui/src/constants.ts
> Update FoAI course links

- apps/infra/Pulumi.prod.yaml
- apps/infra/src/k8s/secrets.ts
- apps/infra/src/k8s/serviceDefinitions.ts
- apps/login/Dockerfile
- apps/login/package.json
Reverts bluedotimpact/bluedot#685
Not sure why but I think this makes things unhappy
> Revert "login: Update keycloak version"

- apps/app-template/package.json
- apps/availability/package.json
- apps/backend/package.json
- apps/course-demos/package.json
- apps/frontend-example/package.json
- apps/infra/package.json
- apps/login-account-proxy/package.json
- apps/meet/package.json
- apps/room/package.json
- apps/storybook/package.json
- apps/website-25/package.json
- libraries/backend-contract/package.json
- libraries/eslint-config/package.json
- libraries/ui/package.json
- package-lock.json
ESLint has been running slowly for me - it's possible that this would speed it up based on https://github.com/typescript-eslint/typescript-eslint/issues/1192
Also generally good to keep deps up to date :)
> devex: Bump TypeScript version

- package-lock.json
- package.json
Generally good to get latest bugfixes etc.
> devex(chore): Upgrade turborepo

- apps/website-25/src/components/courses/Callout.tsx
- apps/website-25/src/components/courses/MarkdownExtendedRenderer.tsx
- apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
- apps/website-25/src/globals.css
Address review feedback from the team on various bits of MDX content formatting
Also shifted some styles from global.css over to the component
> website-25: Tidy up MDX and prose styles

- apps/website-25/src/components/courses/exercises/MultipleChoice.tsx
Add isSubmitting state to MCQ
https://github.com/user-attachments/assets/dafbdf6d-296d-40cd-b104-603ac6120482
> Add isSubmitting state to MCQ

- apps/website-25/src/lib/api/db/tables.ts
- apps/website-25/src/pages/api/certificates/[certificateId].ts
- apps/website-25/src/pages/api/course-registrations/[courseId]/index.tsx
- apps/website-25/src/pages/api/course-registrations/[courseSlug]/index.tsx
- apps/website-25/src/pages/api/course-registrations/index.tsx
- apps/website-25/src/pages/api/users/me.ts
- apps/website-25/src/pages/courses/[courseSlug]/[unitId].tsx
- apps/website-25/src/pages/profile.tsx
- libraries/ui/src/default-config/next.js
Record and process course registrations
Fixes #734
Fixes #735
- Add API for getting all course registrations
- Add API for getting a single course registration for a course. Creates the registration if one does not exist
- Removes enrolledCourses from /me response (given this is now just the same as getting all course registrations)
- Call the API to ensure a course registration exists when viewing unit content
- Update profile page to display all accepted course registrations, and display that whether they are complete (assumes complete = has certificate, which is true for all courses since 2023. we don't have any other measure of complete)
When loading the units page, a course registration is created:
> website-25: Record and process course registrations

- apps/website-25/src/pages/courses/[courseSlug]/index.tsx
Update FOAI copy quickly
https://bluedotimpact.slack.com/archives/C08LQKWBX9B/p1745584841880189
```
```
> Update FOAI copy quickly

- apps/website-25/src/components/Nav.test.tsx
- apps/website-25/src/components/Nav.tsx
- apps/website-25/src/components/__snapshots__/Nav.test.tsx.snap
website-25: Login from Nav should maintain the URL
Fixes #752
https://github.com/user-attachments/assets/86cd0aff-0a73-4c40-8fdc-04689061cd18
> website-25: Login from Nav should maintain the URL

- apps/website-25/src/components/courses/CertificateLinkCard.tsx
- apps/website-25/src/components/courses/UnitFeedback.tsx
- apps/website-25/src/components/courses/UnitLayout.test.tsx
- apps/website-25/src/components/courses/UnitLayout.tsx
- apps/website-25/src/components/courses/__snapshots__/UnitFeedback.test.tsx.snap
- apps/website-25/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
- apps/website-25/src/lib/api/db/tables.ts
- apps/website-25/src/pages/api/certificates/request.ts
- apps/website-25/src/pages/api/course-registrations/[courseId]/index.tsx
- apps/website-25/src/pages/courses/[courseSlug]/[unitId].tsx
- libraries/ui/src/ErrorSection.test.tsx
- libraries/ui/src/ErrorSection.tsx
- libraries/ui/src/ErrorView.tsx
Add certificate creation. Copilot gives a good summary:
- A new API endpoint for requesting certificates, with exercise completion validation.
- Updates to course registration and error handling components to support certificate creation.
- Modifications to the course unit page and layout to display certificate-related links and messaging.
There are also a few incidental changes to:
- Make course registration fetching use useAxios, so it's cached and we make less network requests
- Add ErrorView, which is the body of ErrorSection. Also some styling tweaks so its properties don't blow up the width of the ErrorSection container at the right size
Fixes #569
https://github.com/user-attachments/assets/fe7c263a-7a50-445e-b108-1a3ade496ff9
> website-25: Add certificate creation

- apps/course-demos/src/pages/s/[savedDemoOutputId].tsx
- apps/website/src/components/Nav.stories.tsx
- apps/website/src/pages/api/certificates/[certificateId].ts
> demos,website: Update FOAI course link

- apps/app-template/src/components/ExampleComponent.tsx
- apps/app-template/src/pages/authed.tsx
- apps/app-template/src/pages/index.tsx
> app-template: Use new design system components

- apps/course-demos/src/components/CodeRenderer.tsx
- apps/course-demos/src/pages/2018-to-present/index.tsx
- apps/course-demos/src/pages/generate-react-component.tsx
- apps/course-demos/src/pages/index.tsx
- apps/course-demos/src/pages/s/[savedDemoOutputId].tsx
- libraries/ui/src/ShareButton.tsx
Part of #749
Exception: LinkOrButton, because I think this should probably have its own PR where we migrate everything onto this, likely related to #748
Before
<details><summary>2018 to present</summary>
<p>
</p>
</details> 
<details><summary>Generate react component</summary>
<p>
</p>
</details> 
After
<details><summary>2018 to present</summary>
<p>
</p>
</details> 
<details><summary>Generate react component</summary>
<p>
</p>
</details>
> course-demos: Use new design system components

- apps/room/src/pages/[roomId].tsx
- apps/room/src/pages/_app.tsx
- apps/room/src/pages/display/[roomId].tsx
- apps/room/src/pages/index.tsx
Part of #749
Exception: LinkOrButton, because I think this should probably have its own PR where we migrate everything onto this, likely related to #748
> room: Use new design system components

- apps/meet/src/components/AppJoinView.tsx
- apps/meet/src/components/Page.tsx
- apps/meet/src/components/SelectPersonView.tsx
- apps/meet/src/components/Text.tsx
- apps/meet/src/pages/record-attendance.tsx
- apps/website/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website/src/__tests__/pages/__snapshots__/join-us.test.tsx.snap
- apps/website/src/components/__snapshots__/Nav.test.tsx.snap
- apps/website/src/components/about/__snapshots__/JoinUsCta.test.tsx.snap
- apps/website/src/components/about/__snapshots__/TeamSection.test.tsx.snap
- apps/website/src/components/courses/__snapshots__/UnitFeedback.test.tsx.snap
- apps/website/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
- apps/website/src/components/courses/exercises/__snapshots__/FreeTextResponse.test.tsx.snap
- apps/website/src/components/courses/exercises/__snapshots__/MultipleChoice.test.tsx.snap
- apps/website/src/components/homepage/CommunitySection/__snapshots__/ProjectsSubSection.test.tsx.snap
- apps/website/src/components/homepage/__snapshots__/BlogSection.test.tsx.snap
- apps/website/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- apps/website/src/components/join-us/__snapshots__/CareersSection.test.tsx.snap
- libraries/ui/src/CTALinkOrButton.tsx
- libraries/ui/src/__snapshots__/Banner.test.tsx.snap
- libraries/ui/src/__snapshots__/CTALinkOrButton.test.tsx.snap
- libraries/ui/src/__snapshots__/Card.test.tsx.snap
- libraries/ui/src/__snapshots__/CookieBanner.test.tsx.snap
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
- libraries/ui/src/__snapshots__/HeroSection.test.tsx.snap
The buttons look a little clunky, but okay enough for now.
Part of #749
Exception: LinkOrButton, because I think this should probably have its own PR where we migrate everything onto this, likely related to #748
> meet: Use new design system components

- .github/workflows/website_deploy_production.yaml
- apps/website/README.md
Reduce the number of steps and amount of typing it takes to create a website release
> website: Simplify deployment process

- apps/website/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- libraries/ui/src/CourseCard.tsx
- libraries/ui/src/__snapshots__/CourseCard.test.tsx.snap
Quick copy fix on CourseCard
```
```
> Quick copy fix on CourseCard

- apps/infra/Pulumi.prod.yaml
- apps/infra/src/k8s/postgres.ts
- apps/infra/src/k8s/secrets.ts
- apps/infra/src/k8s/serviceDefinitions.ts
- apps/login-old/Dockerfile
- apps/login-old/README.md
- apps/login-old/package.json
- apps/login-old/tools/getBluedotKeycloakTheme.sh
- apps/login/Dockerfile
- package-lock.json
I created a new app this time so that we don't take down production keycloak
Working towards #679, and #761
> login: Try updating Keycloak again

- apps/login/Dockerfile
See https://github.com/keycloak/keycloak/issues/38893
> login: Fix 'A provider JAR was updated since the last build' error

- apps/website/src/pages/404.tsx
In line with Google SEO best practices
https://developers.google.com/search/docs/crawling-indexing/javascript/javascript-seo-basics#avoid-soft-404s
> website: Disable indexing 404 pages

- apps/website/src/components/courses/Embed.tsx
Fixes .svg images rendering in blog articles
> website: Embed: add support for more image types

- apps/website/src/__tests__/pages/__snapshots__/join-us.test.tsx.snap
- apps/website/src/components/join-us/ValuesSection.tsx
- apps/website/src/components/join-us/__snapshots__/ValuesSection.test.tsx.snap
Update the values section to our new set of values.
I've come up with the subtitle wording after a lot of back-and-forth with Claude. I think this is good but feedback welcomed!
Also I haven't made new images - it probably would be nice to do so. But the current icons work okayish with the values, if we swap a couple of them around.
Fixes #847
> website: Update values section

- apps/website/src/components/courses/exercises/MultipleChoice.tsx
- apps/website/src/components/courses/exercises/__snapshots__/MultipleChoice.test.tsx.snap
Fixes #858
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details>
> website: Fix MCQ exercise spacing

- apps/app-template/src/lib/api/makeApiRoute.ts
- apps/availability/src/lib/api/makeApiRoute.ts
- apps/course-demos/src/lib/api/makeApiRoute.ts
- apps/course-demos/src/pages/api/generate-react-component.ts
- apps/frontend-example/src/lib/api/makeApiRoute.ts
- apps/login-account-proxy/src/lib/api/makeApiRoute.ts
- apps/login-account-proxy/src/pages/api/public/is-password-migrated.ts
- apps/login-account-proxy/src/pages/api/public/submit.ts
- apps/meet/src/lib/api/makeApiRoute.ts
- apps/room/src/lib/api/makeApiRoute.ts
- apps/website/src/instrumentation.ts
- apps/website/src/lib/api/makeApiRoute.ts
- libraries/ui/README.md
- libraries/ui/package.json
- libraries/ui/src/api.ts
- libraries/ui/src/default-config/instrumentation.ts
- libraries/ui/src/default-config/next.js
- libraries/ui/src/index.ts
- libraries/ui/src/utils/logger.ts
- libraries/ui/src/utils/makeMakeApiRoute.ts
- package-lock.json
Related to #680 
- libraries/ui: Move server-side utils to separate api.ts
- Add instrumentation config
- Add winston logging library
- Add span/tracing setup in makeMakeApiRoute
> observability: Add structured logging and basic metrics to website

- apps/website-proxy/src/nginx.template.conf
We've tried to audit everything, but will see who shouts at us over the weekend about things breaking 😅
> website-proxy: Migrate entirely to new website

- apps/website/src/pages/code-of-conduct.tsx
> website: Add code of conduct page

- apps/website/src/pages/our-community.tsx
> website: Add our-community page

- apps/website/src/pages/resources.tsx
> website: Add resources page

- apps/editor/src/components/BaseLayout.tsx
- apps/editor/src/lib/api/db/tables.ts
- apps/editor/src/pages/api/projects/[slug]/index.ts
- apps/editor/src/pages/api/projects/index.ts
- apps/editor/src/pages/projects/[slug].tsx
- apps/editor/src/pages/projects/index.tsx
- apps/website/src/pages/api/cms/blogs/[slug]/index.ts
Adds support to edit project bodies in the editor app
Also tidied up a couple of TODOs
Fixes #895
https://github.com/user-attachments/assets/af39cb24-5b93-435e-b8c4-04328bb9687b
> editor: Add support for editing projects

- apps/editor/src/lib/api/db/tables.ts
- apps/website/src/components/blog/BlogListSection.tsx
- apps/website/src/components/projects/ProjectsListSection.tsx
- apps/website/src/lib/api/db/tables.ts
- apps/website/src/lib/routes.ts
- apps/website/src/pages/api/cms/projects/[slug]/index.ts
- apps/website/src/pages/api/cms/projects/index.ts
- apps/website/src/pages/blog/[slug].tsx
- apps/website/src/pages/projects/[slug].tsx
- apps/website/src/pages/projects/index.tsx
website: Add project list and details pages
Fixes #896, fixes #897
> website: Add project list and details pages

- apps/website/src/components/homepage/CommunitySection/ProjectsSubSection.tsx
- apps/website/src/components/homepage/CommunitySection/__snapshots__/ProjectsSubSection.test.tsx.snap
> website: Update projects on homepage

- apps/website/src/pages/blog/[slug].tsx
> website: Add BlogPosting Schema.org markup

- apps/website/src/lib/api/db/tables.ts
- apps/website/src/pages/join-us/[slug].tsx
> website: Add JobPosting schema.org markup

- apps/website/public/icons/course.svg
This had multiple stacked layers that weren't being used, but caused rendering artifacts.
Minimal visual changes - can be previewed in 'Files changed' tab
> website(nit): tidy up course.svg

- apps/website/src/pages/certification.tsx
- apps/website/src/pages/running-versions-of-our-courses.tsx
Clean up from migrating from course.bluedot.org
> website: Remove references to course.bluedot.org

- apps/room/package.json
- package-lock.json
> room: Remove airtable-ts

- apps/website/src/components/community/CircleWidget.tsx
- apps/website/src/components/lander/FutureOfAiLander.tsx
- apps/website/src/components/lander/__snapshots__/FutureOfAiLander.test.tsx.snap
This replaces the old community modal with a new one from Front.com. It also adds a CTA button to join our community on the Future of AI page. 
Fixes https://github.com/bluedotimpact/bluedot/issues/1065
https://github.com/user-attachments/assets/f5b59893-978f-4c8f-8684-a2a0adbf5856
> feat: add join the community call to action button to foai page

- libraries/db/src/schema.ts
This is just a quick PR to add new fields to the db sync that I need for the follow up PR.
> feat: add last visited unit and chunk to db sync

- apps/website/src/components/courses/UnitLayout.test.tsx
- apps/website/src/components/courses/UnitLayout.tsx
- apps/website/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
Use arrow keys to navigate backwards and forwards in the unit pages.
Fixes #1051 
Not applicable
> [Feature] Arrow keys for unit navigation

- DEVELOPMENT_HANDBOOK.md
The newly created developer docs didn't have some crucial information regarding deployment and observability in them. I added this to save some time for the next person.
> feat: add more info to deployment and devops section

- apps/website/src/components/about/IntroSection.tsx
Fixed squishing of Will and Dewi:
> fix(website/about): squished pic under firefox

- .github/workflows/auto-label-priority.yml
Fixes parsing issue 
| 📸 |  |
| 📱  |  |
| 🖥️ |  |
> Update auto-label-priority.yml to fix parsing issue

- .github/workflows/auto-label-priority.yml
Fixes labels not mapping properly
| 📸 |  |
| 📱  |  |
| 🖥️ |  |
> Update auto-label-priority.yml to fixe labelling

- apps/website/src/components/courses/StarRating.tsx
- apps/website/src/components/courses/__snapshots__/StarRating.test.tsx.snap
- apps/website/src/components/courses/__snapshots__/UnitFeedback.test.tsx.snap
Adds hover hint text on star rating feedback component across all courses:
★☆☆☆☆ - Struggled to understand key concepts
★★☆☆☆ - Understood basics but found it challenging
★★★☆☆ - Learned adequately but had some difficulty
★★★★☆ - Learned well and felt appropriately challenged
★★★★★ - Mastered concepts with confidence
Fixes #652
> [feat]: hover hint text on feedback component

- apps/website/src/components/courses/CourseDirectory.stories.tsx
- libraries/db/src/schema.ts
Needed to filter dropped out users from courses before we let people cohort switch. 
Working towards #571 and #572 
Not really applicable, this is just syncing Airtable with Postgres. I'll have a follow up that implments the frontend and backend changes.
Not applicable
> [Feature] Start syncing dropped out status for courses

- apps/website/src/components/courses/Embed.tsx
Fixed audio not working in the Suno audio embedding with custom player.
Fixes #1143
> [fix + feat]: audio embedding and custom player

- apps/website/src/__tests__/pages/__snapshots__/about.test.tsx.snap
- apps/website/src/pages/about.tsx
Fixes #
| 📸 |  |
| 📱  |  |
| 🖥️ |  |
> [Typo] Fixing typo in mission statement on about page

- apps/website/src/components/courses/exercises/Exercise.tsx
- apps/website/src/components/courses/exercises/FreeTextResponse.test.tsx
- apps/website/src/components/courses/exercises/FreeTextResponse.tsx
- apps/website/src/components/courses/exercises/SaveStatusIndicator.test.tsx
- apps/website/src/components/courses/exercises/SaveStatusIndicator.tsx
- apps/website/src/components/courses/exercises/__snapshots__/FreeTextResponse.test.tsx.snap
- apps/website/src/globals.css
Implementing autosave functionality in exercises, updating UI and adding ARIA support.
Fixes #1152
> [feat]: autosave functionality + exercise ui update

- libraries/db/src/schema.ts
This PR bundles several database related changes together. I decided to combine them into a single PR rather than doing them separately because:
Since we had recent syncing issues, it's easier to only watch the sync once for all of the new fields at once rather than one at a time.
Several features require these new changes, so doing them all at once unblocks multiple features.
Unblocks feature development for #1147 #1148 #1149
N/A
N/A
> [Feature] Database schema changes for all of the courses redesign

- apps/website/src/components/lander/AgiStrategyLander.tsx
interest form link becomes application form link
Fixes # 
| 📸 |  |
| 📱  |  |
| 🖥️ |  |
> Update AgiStrategyLander with application link

- apps/website/src/components/courses/ResourceListCourseContent.tsx
- apps/website/src/components/courses/UnitLayout.tsx
- apps/website/src/components/courses/__snapshots__/UnitLayout.test.tsx.snap
Fixing a range of UX bugs. Used a combo of Cline and Windsurf to write the code, with Claude 4 Sonnet as the base model. This is vibe-coded; I have not verified the code is high-quality. 
Before on the left, after on the right. 
Changes include fixed padding around components, removing the learning objectives section, rounding up the resource estimate numbers, adding cursor pointers, and centering the content when the sidebar is closed.
> [Bug] Misc UX bug bash

- apps/website/src/components/Nav/__snapshots__/Nav.test.tsx.snap
- libraries/ui/src/default-config/tailwind.css
This is updating the background colour to match the new courses ui.
Fixes [#1176](https://github.com/bluedotimpact/bluedot/issues/1176)
> feat: update background color

- libraries/db/src/schema.ts
Making the db changes so that I can do #1214. Used pg-sync-service locally to test if I had the right types. 
Related to #1214
Not applicable
Not applicable
> [feature] Updating schema to prepare chunks to have resources and exercises

- libraries/db/src/schema.ts
Need these fields to get the expected discussions for participants and facilitators.
#1210 , #1217 
Fixes #
No frontend changes.
| 📸 |  |
| 📱  |  |
| 🖥️ |  |
> Added fields to CR course registration table for displaying upcoming sessions

- apps/website/src/components/lander/FutureOfAiLander.tsx
- apps/website/src/components/lander/__snapshots__/FutureOfAiLander.test.tsx.snap
Fixed mobile layout issues for FOAI (text/buttons cutoff, insufficient padding, poor responsive behavior on smaller screen sizes).
- Refactored the hero banner to use a mobile-first responsive approach with Tailwind breakpoints instead of JavaScript device detection
- Separated quotes into a dedicated section below hero on mobile for better readability
- Retains desktop design at larger screen sizes
Fixes #1218 
| Before  | After |
| ------------- | ------------- |
| ![FOAI-mobile-before](https://github.com/user-attachments/assets/bd51da75-3eb2-49b4-b96b-e2770318dc47) | ![FOAI-mobile-after](https://github.com/user-attachments/assets/3987d29d-8c91-486a-b5ff-62086afeffb5) |
> [feat + fix]: FOAI mobile layout issues

- libraries/db/src/schema.ts
Fixing syncing issues because of incorrect schema
(https://github.com/bluedotimpact/bluedot/commit/5e419368c56fbe5d05df09ea582826f504c03e9b)
N/A
N/A
> Changing year back to text

- apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap
- apps/website/src/components/lander/agi-strategy/HeroSection.tsx
- apps/website/src/components/lander/agi-strategy/__snapshots__/HeroSection.test.tsx.snap
Implementing new consistent landing page alignment and fixed max-width when zooming out less than 100%.
**Note:** While the figma design has the hero image stretching to the right at larger screen sizes, to prevent layout distortion and maintain alignment at varied screen sizes I limited the image width to the edge of the container.
Related to #1287 and #1297
> [feat + fix]: agi strategy new landing alignment + fix maxwidth

- apps/website/src/pages/courses/[courseSlug]/[unitNumber]/[[...chunkNumber]].tsx
There is a general bug with auth at the moment, and this is blocking the entire course page from loading (where most of it can be viewed logged out)
> [Bug] Allow groupDiscussion route error in /courses/course/1/1 page

- apps/website/src/pages/_app.tsx
the outage is over! we're back up - this lets returning users know. 
returning users now know that functionality has been restored
Fixes #
| 📸 |  |
| 📱  |  |
| 🖥️ |  |
> updates banner to reflected end of vultr outage

- apps/website/src/components/lander/AgiStrategyLander.tsx
- apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap
- apps/website/src/components/lander/agi-strategy/WhyTakeThisCourseSection.test.tsx
- apps/website/src/components/lander/agi-strategy/WhyTakeThisCourseSection.tsx
- apps/website/src/components/lander/agi-strategy/__snapshots__/WhyTakeThisCourseSection.test.tsx.snap
Implementing the new "why take this course" section in the agi strategy lander. Added new snapshot tests.
**Special notes:**
- **Component isolation:** Implemented in a dedicated agi-strategy dir rather than adding to a shared library, allowing for gradual adoption across other landing pages when needed (we currently need to maintain UI library styles in other pages)
- This PR is part of a series of updates to implement portions of the full AGI Strategy Lander design in #1287  so that changes can be shipped faster (+ while waiting for final copy/icons necessary for other sections in the design)
- Since icons are still being determined, I added a few potentially-fitting ones in the meantime (can be swapped later)
- This is a new landing page specifically for this course. We don't have a …
> [feat]: why take this course section

- apps/website/src/components/blog/BlogListSection.tsx
- apps/website/src/components/homepage/CourseSection.tsx
- apps/website/src/components/homepage/StorySection.tsx
- apps/website/src/components/homepage/__snapshots__/CourseSection.test.tsx.snap
- apps/website/src/components/homepage/__snapshots__/StorySection.test.tsx.snap
- apps/website/src/components/lander/AgiStrategyLander.test.tsx
- apps/website/src/components/lander/AgiStrategyLander.tsx
- apps/website/src/components/lander/__snapshots__/AgiStrategyLander.test.tsx.snap
- apps/website/src/components/lander/agi-strategy/CommunityMembersSubSection.tsx
- apps/website/src/components/lander/agi-strategy/HeroSection.tsx
- apps/website/src/globals.css
- apps/website/src/pages/index.tsx
- libraries/ui/src/CourseCard.tsx
- libraries/ui/src/Footer.tsx
- libraries/ui/src/default-config/tailwind.css
- Updated copy/content on the main landing page and the AGI Strategy course. 
- Built a new component for community member shoutouts, which emphasises the profile of the person rather than their quote. 
- Deleted many components from the main website landing page. 
| Description | **Before** and **After** | 
| -- | ------ | 
| BlueDot landing page top | <img width="4112" height="2572" alt="CleanShot 2025-09-10 at 21 11 53@2x" src="https://github.com/user-attachments/assets/6ff1c30a-d188-43b8-aabb-9919b2e21252" /> | 
| BlueDot landing page bottom |<img width="4112" height="2572" alt="CleanShot 2025-09-10 at 21 12 02@2x" src="https://github.com/user-attachments/assets/d243ed8c-82d6-4616-ae9f-1be2f4e1146b" /> |
| AGI Strategy landing page top | <img width="4112" height="2572" alt="CleanShot …
> [Feat] Updated landing page copy, and deleting many components

- apps/website/src/components/courses/GroupSwitchModal.tsx
Adds an ErrorSection so users can report any errors that occur on submission
#1352
N/A
| 📸 |  |
| 📱  |  |
| 🖥️ | <img width="3012" height="1636" alt="Screenshot 2025-09-16 at 22 45 08" src="https://github.com/user-attachments/assets/ecffd7de-7f07-4b3f-bdfb-a02edaddfa3e" /> |
> Display errors in GroupSwitchModal

- libraries/db/src/schema.ts
Schema changes for the course curriculum section in the AGI strategy lander - adding courseUnit
Related to #1334
> [schema] adding courseUnit for course curriculum section

- apps/storybook/.storybook/preview.tsx
- apps/storybook/package.json
- apps/storybook/public/mockServiceWorker.js
- package-lock.json
While working on #1347 I was getting very frustrated waiting for full page reloads (and waiting for requests to complete) just so I could preview changes. I decided to start working on stories for the `GroupModalSwitch` component. Since this component makes several API calls I needed to mock them, which led me to: https://storybook.js.org/docs/writing-stories/mocking-data-and-modules/mocking-network-requests and these changes.
Separating out for smaller PRs.
NA
NA
> Storybook Mock Service Worker (MSW)

- apps/website/src/components/Nav/_NavLinks.tsx
- apps/website/src/components/Nav/__snapshots__/Nav.test.tsx.snap
- apps/website/src/components/courses/CertificateLinkCard.test.tsx
- apps/website/src/components/courses/__snapshots__/Congratulations.test.tsx.snap
- apps/website/src/components/courses/__snapshots__/FoAICongratulations.test.tsx.snap
- apps/website/src/components/courses/__snapshots__/SocialShare.test.tsx.snap
- apps/website/src/components/lander/__snapshots__/FutureOfAiLander.test.tsx.snap
- libraries/ui/src/ClickTarget.tsx
Add new Shop navigation link pointing to https://shop.bluedot.org/ in the main navigation component. Updated corresponding test snapshots to reflect the new navigation item.
| Before and After |
| ---| 
| <img width="5120" height="2880" alt="CleanShot 2025-09-20 at 14 35 02@2x" src="https://github.com/user-attachments/assets/498bf7ec-14f1-4cd0-94da-ee0e8d22dab0" /> |
> [Feat] Adding "shop" to the navbar.

- apps/website/src/components/lander/agi-strategy/CourseDetailsSection.tsx
updates applications deadlines to be curretn! 
Fixes #
| 📸 |  |
| 📱  |  |
| 🖥️ |  |
> Update AGI Strat round dates

- apps/editor/src/pages/api/jobs/index.ts
Fixes #
| 📸 |  |
| 📱  |  |
| 🖥️ |  |
> Improve job listings sort order by recency in editor

- apps/website/package.json
- apps/website/src/__tests__/testUtils.ts
- apps/website/src/components/settings/CourseDetails.test.tsx
- apps/website/src/components/settings/CourseListRow.test.tsx
- apps/website/src/components/settings/CourseListRow.tsx
> `CourseListRow` test mock time

- apps/website/src/components/courses/GroupDiscussionBanner.stories.tsx
- apps/website/src/components/courses/GroupDiscussionBanner.test.tsx
- apps/website/src/components/courses/__snapshots__/GroupDiscussionBanner.test.tsx.snap
- apps/website/src/pages/api/courses/[courseSlug]/[unitNumber]/groupDiscussion.ts
- apps/website/src/test-setup.ts
- apps/website/vitest.config.mjs
Added while I was doing #1387, split out into a separate PR because the tests are mostly not related to that change
| 📸 |  |
| | <img width="2214" height="1514" alt="Screenshot 2025-09-25 at 11 52 53" src="https://github.com/user-attachments/assets/8145f216-0e39-47b1-a1a9-1c4dbde44220" /> |
| | <img width="2214" height="1514" alt="Screenshot 2025-09-25 at 11 52 46" src="https://github.com/user-attachments/assets/2e9a946e-9650-4155-8ebb-25634b8097b8" /> |
> [Feature] Add tests and stories for GroupDiscussionBanner
